-- =====================================================================
-- CR-022 : shop GST/address settings, Customer address/state, Quotation
-- (Module 10, built ahead of Purchase/Inventory - price document only,
-- no stock movement, no dependency on either). See CR-022 for the full
-- reasoning, including why the GST split is computed at PDF render time
-- rather than stored.
-- =====================================================================

-- ---------------------------------------------------------------------
-- tenant : shop's own GST/address, printed on every invoice/quotation
-- PDF. All nullable - a shop that hasn't filled in Settings yet still
-- trades; the PDF prints "Not set" rather than failing.
-- ---------------------------------------------------------------------
ALTER TABLE tenant
    ADD COLUMN gst_no         VARCHAR(15),
    ADD COLUMN address_line1  VARCHAR(255),
    ADD COLUMN address_line2  VARCHAR(255),
    ADD COLUMN city           VARCHAR(100),
    ADD COLUMN state_code     VARCHAR(2),
    ADD COLUMN pincode        VARCHAR(6),
    ADD COLUMN signatory_name VARCHAR(100);

-- ---------------------------------------------------------------------
-- customer : address/state needed for the "Bill to" block and for the
-- CGST+SGST vs IGST split (compares customer.state_code to
-- tenant.state_code). gst_no already existed (CR-021) but was never
-- settable from the Invoice flow until this CR.
-- ---------------------------------------------------------------------
ALTER TABLE customer
    ADD COLUMN address_line1 VARCHAR(255),
    ADD COLUMN address_line2 VARCHAR(255),
    ADD COLUMN city          VARCHAR(100),
    ADD COLUMN state_code    VARCHAR(2),
    ADD COLUMN pincode       VARCHAR(6);

-- ---------------------------------------------------------------------
-- quotation : structurally identical to invoice minus every payment
-- column. Not a financial record - no stock movement, no GST posting -
-- until converted. valid_until past today blocks conversion.
-- ---------------------------------------------------------------------
CREATE TABLE quotation (
    quotation_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id            BIGINT        NOT NULL,
    quotation_number     VARCHAR(30)   NOT NULL,
    customer_id           BIGINT        NOT NULL,
    quotation_date        DATE          NOT NULL,
    valid_until            DATE          NOT NULL,
    subtotal_paise        BIGINT        NOT NULL,
    gst_amount_paise      BIGINT        NOT NULL,
    total_paise           BIGINT        NOT NULL,
    status                 VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    remarks                VARCHAR(500),
    converted_invoice_id   BIGINT,
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT pk_quotation PRIMARY KEY (quotation_id),
    CONSTRAINT fk_quotation_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_quotation_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT fk_quotation_invoice FOREIGN KEY (converted_invoice_id)
        REFERENCES invoice (invoice_id),
    CONSTRAINT uk_quotation_number UNIQUE (tenant_id, quotation_number),
    CONSTRAINT ck_quotation_status CHECK (
        status IN ('DRAFT', 'SENT', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CONVERTED')),
    CONSTRAINT ck_quotation_amounts CHECK (
        subtotal_paise >= 0 AND gst_amount_paise >= 0 AND total_paise >= 0)
);

CREATE INDEX idx_quotation_tenant   ON quotation (tenant_id);
CREATE INDEX idx_quotation_customer ON quotation (customer_id);
CREATE INDEX idx_quotation_status   ON quotation (tenant_id, status);

CREATE TRIGGER trg_quotation_updated_at
    BEFORE UPDATE ON quotation
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE quotation_item (
    quotation_item_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    quotation_id           BIGINT        NOT NULL,
    product_id              BIGINT        NOT NULL,
    product_name_snapshot   VARCHAR(255)  NOT NULL,
    quantity                 DECIMAL(18,4) NOT NULL,
    unit_price_paise         BIGINT        NOT NULL,
    gst_rate_percent         DECIMAL(5,2)  NOT NULL DEFAULT 0,
    line_subtotal_paise      BIGINT        NOT NULL,
    line_gst_paise           BIGINT        NOT NULL,
    line_total_paise         BIGINT        NOT NULL,
    CONSTRAINT pk_quotation_item PRIMARY KEY (quotation_item_id),
    CONSTRAINT fk_quotation_item_quotation FOREIGN KEY (quotation_id)
        REFERENCES quotation (quotation_id) ON DELETE CASCADE,
    CONSTRAINT fk_quotation_item_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT ck_quotation_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_quotation_item_amounts CHECK (
        unit_price_paise >= 0 AND line_subtotal_paise >= 0
        AND line_gst_paise >= 0 AND line_total_paise >= 0)
);

CREATE INDEX idx_quotation_item_quotation ON quotation_item (quotation_id);
CREATE INDEX idx_quotation_item_product   ON quotation_item (product_id);
