-- =====================================================================
-- CR-027 : NOTIFICATION LOG
--
-- Every outbound customer/staff notification attempt (email, SMS,
-- WhatsApp), whether it actually left the building or was only logged
-- because no real SMS/WhatsApp provider is configured yet. This is the
-- shop owner's answer to "did my customer actually get notified" - not a
-- queue, not a retry mechanism, just an audit trail. Modelled on
-- activity_log / security_audit_log: plain tenant_id column (no FK object
-- needed on the entity side), append-only, no updated_at/updated_by.
-- =====================================================================

CREATE TABLE notification_log (
    notification_log_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id            BIGINT       NOT NULL,
    channel              VARCHAR(20)  NOT NULL,
    recipient            VARCHAR(255) NOT NULL,
    subject              VARCHAR(255),
    body                 VARCHAR(1000) NOT NULL,
    status               VARCHAR(20)  NOT NULL,
    related_entity_type  VARCHAR(60),
    related_entity_id    BIGINT,
    created_at           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_notification_log PRIMARY KEY (notification_log_id),
    CONSTRAINT fk_notification_log_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT ck_notification_log_channel CHECK (
        channel IN ('EMAIL', 'SMS', 'WHATSAPP')),
    CONSTRAINT ck_notification_log_status CHECK (
        status IN ('SENT', 'LOGGED_ONLY', 'FAILED'))
);

CREATE INDEX idx_notification_log_tenant  ON notification_log (tenant_id, created_at DESC);
CREATE INDEX idx_notification_log_related ON notification_log (related_entity_type, related_entity_id);

COMMENT ON TABLE notification_log IS
    'Audit trail of every outbound notification attempt (CR-027). LOGGED_ONLY means no real SMS/WhatsApp provider is configured - see app.notifications.sms.* / app.notifications.whatsapp.*.';
