-- =====================================================================
-- CR-028 : retail discount coupons. Tenant-scoped, optionally restricted
-- to specific products (an empty coupon_product means "all products").
-- Applied at invoice-creation time only - a coupon never changes a
-- product's own price, it only discounts what a given invoice charges.
-- =====================================================================

CREATE TABLE coupon (
    coupon_id          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id           BIGINT        NOT NULL,
    code                VARCHAR(30)   NOT NULL,
    description         VARCHAR(255),
    discount_type       VARCHAR(10)   NOT NULL,
    -- Interpreted per discount_type: PERCENT is a 0-100 percentage
    -- (e.g. 10.00 = 10%), FLAT is paise (money convention, never a float).
    discount_value      DECIMAL(18,2) NOT NULL,
    min_purchase_paise  BIGINT,
    -- Caps a PERCENT discount's absolute rupee value. Meaningless for
    -- FLAT (the flat amount already is the cap) - left null there.
    max_discount_paise  BIGINT,
    valid_from          DATE,
    valid_until         DATE,
    -- Null = unlimited uses.
    usage_limit         INTEGER,
    times_used          INTEGER       NOT NULL DEFAULT 0,
    status              VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMP(3)  NOT NULL,
    created_by          BIGINT,
    updated_at          TIMESTAMP(3),
    updated_by          BIGINT,
    version             INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT pk_coupon PRIMARY KEY (coupon_id),
    CONSTRAINT fk_coupon_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT ck_coupon_discount_type CHECK (discount_type IN ('PERCENT', 'FLAT')),
    CONSTRAINT ck_coupon_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_coupon_discount_value CHECK (discount_value > 0),
    CONSTRAINT ck_coupon_percent_range CHECK (discount_type <> 'PERCENT' OR discount_value <= 100)
);

CREATE UNIQUE INDEX uk_coupon_code ON coupon (tenant_id, upper(code));
CREATE INDEX idx_coupon_tenant ON coupon (tenant_id, status);

-- Empty for a coupon = applies to every product. Populated = restricted
-- to exactly these products.
CREATE TABLE coupon_product (
    coupon_id  BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT pk_coupon_product PRIMARY KEY (coupon_id, product_id),
    CONSTRAINT fk_coupon_product_coupon FOREIGN KEY (coupon_id) REFERENCES coupon (coupon_id) ON DELETE CASCADE,
    CONSTRAINT fk_coupon_product_product FOREIGN KEY (product_id) REFERENCES product (product_id) ON DELETE CASCADE
);

ALTER TABLE invoice ADD COLUMN coupon_id BIGINT REFERENCES coupon (coupon_id);
ALTER TABLE invoice ADD COLUMN discount_paise BIGINT NOT NULL DEFAULT 0;
ALTER TABLE quotation ADD COLUMN coupon_id BIGINT REFERENCES coupon (coupon_id);
ALTER TABLE quotation ADD COLUMN discount_paise BIGINT NOT NULL DEFAULT 0;

-- ---------------------------------------------------------------------
-- New permissions. Global catalog (permission is not tenant-scoped, see
-- CR-016) - visible to every tenant immediately, but a role only actually
-- holds one once granted. Every existing tenant's OWNER is backfilled
-- here (OWNER holds every permission by invariant, same as V1's seed and
-- TenantRegistrationServiceImpl's default template for new tenants);
-- MANAGER can also manage coupons, ACCOUNTANT/STAFF can view them.
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('COUPON_VIEW',   'View coupons',   'View discount coupons',            'SALES', 22),
 ('COUPON_MANAGE', 'Manage coupons', 'Create and edit discount coupons', 'SALES', 23);

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM role r CROSS JOIN permission p
WHERE r.role_code = 'OWNER' AND p.permission_code IN ('COUPON_VIEW', 'COUPON_MANAGE');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM role r CROSS JOIN permission p
WHERE r.role_code = 'MANAGER' AND p.permission_code IN ('COUPON_VIEW', 'COUPON_MANAGE');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM role r CROSS JOIN permission p
WHERE r.role_code IN ('ACCOUNTANT', 'STAFF') AND p.permission_code = 'COUPON_VIEW';
