-- =====================================================================
-- MODULE 8: PROJECT MANAGEMENT (Phase 6 of the ERP expansion)
--
-- Scope of this migration: work_type (user-extensible, not hardcoded),
-- project (header, with a two-field lifecycle - see the status/outcome
-- note below), project_material (products consumed by a project, supplier
-- deliberately optional), project_expense (a manual ledger for
-- labour/employee/food/stay/petrol/other costs - see the note on why this
-- is manual today, not derived from a Labour module), project_payment
-- (amounts received against the project's contracted value).
--
-- Explicitly NOT in this migration: labour_team / labour_employee /
-- attendance (a separate, later module - project_expense's LABOUR/EMPLOYEE
-- categories are a manual stand-in until that module exists and can
-- populate them automatically), financial_transaction / cash-bank-cheque
-- ledger (separate Finance module), any report tables (reports are
-- computed from existing data, not stored).
-- =====================================================================

CREATE TABLE work_type (
    work_type_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id    BIGINT       NOT NULL,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(500),
    created_at   TIMESTAMP(3) NOT NULL,
    updated_at   TIMESTAMP(3),
    CONSTRAINT pk_work_type PRIMARY KEY (work_type_id),
    CONSTRAINT fk_work_type_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)
);

CREATE UNIQUE INDEX uk_work_type_tenant_name ON work_type (tenant_id, lower(name));

CREATE TRIGGER trg_work_type_updated_at
    BEFORE UPDATE ON work_type
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Seed the common work types the owner's own request named as examples -
-- a convenience starting point, never a restriction: "Add work type" in the
-- UI inserts a plain row here with no code-level enum anywhere.
INSERT INTO work_type (tenant_id, name, description, created_at)
SELECT t.tenant_id, wt.name, wt.description, CURRENT_TIMESTAMP
FROM tenant t
CROSS JOIN (VALUES
    ('Modular Kitchen', NULL),
    ('Stainless Steel Work', NULL),
    ('Iron Gate', NULL),
    ('Rooftop Sheet', NULL),
    ('Mica Sheet Work', NULL),
    ('Glass Work', NULL),
    ('Fabrication', NULL),
    ('Interior Work', NULL),
    ('Custom Work', NULL)
) AS wt(name, description);

-- ---------------------------------------------------------------------
-- project : the two-field lifecycle -
--   status  = where the project is right now (UPCOMING/IN_PROGRESS/
--             ON_HOLD/CANCELLED/COMPLETED) - exactly one value, always.
--   outcome = the business result (SUCCESS/FAILURE), NULL until the
--             project reaches COMPLETED, then set explicitly by whoever
--             closes it out - never auto-inferred from the profit number,
--             since a project can finish on-budget with an unhappy
--             customer or over-budget but still a relationship win.
-- OVERDUE is deliberately not a stored value - like Quotation.isExpired(),
-- it's computed at read time from customer_deadline vs today, so there is
-- only ever one source of truth for "is this late".
-- ---------------------------------------------------------------------
CREATE TABLE project (
    project_id                BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id                 BIGINT        NOT NULL,
    project_number             VARCHAR(20)   NOT NULL,
    project_name               VARCHAR(200)  NOT NULL,
    customer_id                BIGINT        NOT NULL,
    work_type_id               BIGINT        NOT NULL,
    description                VARCHAR(2000),
    site_address                VARCHAR(500),
    start_date                  DATE,
    expected_completion_date     DATE,
    actual_completion_date       DATE,
    customer_deadline           DATE,
    status                      VARCHAR(20)   NOT NULL DEFAULT 'UPCOMING',
    outcome                     VARCHAR(20),
    project_value_paise          BIGINT        NOT NULL DEFAULT 0,
    manager_user_id              BIGINT,
    notes                       VARCHAR(2000),
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    CONSTRAINT pk_project PRIMARY KEY (project_id),
    CONSTRAINT fk_project_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_project_customer FOREIGN KEY (customer_id) REFERENCES customer (customer_id),
    CONSTRAINT fk_project_work_type FOREIGN KEY (work_type_id) REFERENCES work_type (work_type_id),
    CONSTRAINT fk_project_manager FOREIGN KEY (manager_user_id) REFERENCES app_user (user_id),
    CONSTRAINT uk_project_number UNIQUE (tenant_id, project_number),
    CONSTRAINT ck_project_status CHECK (status IN
        ('UPCOMING', 'IN_PROGRESS', 'ON_HOLD', 'CANCELLED', 'COMPLETED')),
    CONSTRAINT ck_project_outcome CHECK (outcome IS NULL OR outcome IN ('SUCCESS', 'FAILURE')),
    CONSTRAINT ck_project_outcome_only_when_completed CHECK (outcome IS NULL OR status = 'COMPLETED'),
    CONSTRAINT ck_project_value CHECK (project_value_paise >= 0)
);

CREATE INDEX idx_project_tenant_customer ON project (tenant_id, customer_id);
CREATE INDEX idx_project_tenant_status ON project (tenant_id, status);

CREATE TRIGGER trg_project_updated_at
    BEFORE UPDATE ON project
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- project_material : supplier is deliberately nullable - some old stock
-- was never recorded with a supplier, and this must never block adding it
-- to a project. unit_price_paise and unit are snapshotted at add-time
-- (never a live join back to product), matching the "cost on a line is a
-- snapshot, not a lookup" rule invoice_item already follows.
-- ---------------------------------------------------------------------
CREATE TABLE project_material (
    project_material_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id            BIGINT        NOT NULL,
    project_id            BIGINT        NOT NULL,
    product_id            BIGINT        NOT NULL,
    supplier_id           BIGINT,
    quantity_required      DECIMAL(18,4),
    quantity_estimated     DECIMAL(18,4),
    quantity_actual        DECIMAL(18,4),
    quantity_wastage       DECIMAL(18,4) NOT NULL DEFAULT 0,
    unit                  VARCHAR(20)   NOT NULL,
    unit_price_paise       BIGINT        NOT NULL,
    total_cost_paise        BIGINT        NOT NULL,
    notes                 VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL,
    updated_at TIMESTAMP(3),
    CONSTRAINT pk_project_material PRIMARY KEY (project_material_id),
    CONSTRAINT fk_project_material_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_project_material_project FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT fk_project_material_product FOREIGN KEY (product_id) REFERENCES product (product_id),
    CONSTRAINT fk_project_material_supplier FOREIGN KEY (supplier_id) REFERENCES supplier (supplier_id),
    CONSTRAINT ck_project_material_cost CHECK (unit_price_paise >= 0 AND total_cost_paise >= 0)
);

CREATE INDEX idx_project_material_project ON project_material (project_id);

CREATE TRIGGER trg_project_material_updated_at
    BEFORE UPDATE ON project_material
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- project_expense : a manual ledger today. LABOUR/EMPLOYEE amounts are
-- typed in by hand for now - once the Labour/Team/Attendance module
-- exists (a later, separate phase), those categories become derived from
-- real attendance records instead, but the project's profitability math
-- must work correctly today, not only after every future module ships.
-- ---------------------------------------------------------------------
CREATE TABLE project_expense (
    project_expense_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id            BIGINT        NOT NULL,
    project_id            BIGINT        NOT NULL,
    category              VARCHAR(20)   NOT NULL,
    amount_paise           BIGINT        NOT NULL,
    expense_date           DATE          NOT NULL,
    paid_to                VARCHAR(200),
    description           VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_project_expense PRIMARY KEY (project_expense_id),
    CONSTRAINT fk_project_expense_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_project_expense_project FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT ck_project_expense_category CHECK (category IN
        ('LABOUR', 'EMPLOYEE', 'FOOD', 'STAY', 'PETROL', 'OTHER')),
    CONSTRAINT ck_project_expense_amount CHECK (amount_paise >= 0)
);

CREATE INDEX idx_project_expense_project ON project_expense (project_id);

-- ---------------------------------------------------------------------
-- project_payment : amounts received against the project's contracted
-- value (project.project_value_paise) - a lighter-weight ledger than the
-- Invoice module's payment table, since a project isn't always invoiced
-- 1:1. payment_method reuses invoice.payment's exact value set.
-- ---------------------------------------------------------------------
CREATE TABLE project_payment (
    project_payment_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id            BIGINT        NOT NULL,
    project_id            BIGINT        NOT NULL,
    amount_paise           BIGINT        NOT NULL,
    payment_method         VARCHAR(20)   NOT NULL,
    payment_date            DATE          NOT NULL,
    notes                 VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_project_payment PRIMARY KEY (project_payment_id),
    CONSTRAINT fk_project_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_project_payment_project FOREIGN KEY (project_id) REFERENCES project (project_id),
    CONSTRAINT ck_project_payment_method CHECK (
        payment_method IN ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER')),
    CONSTRAINT ck_project_payment_amount CHECK (amount_paise > 0)
);

CREATE INDEX idx_project_payment_project ON project_payment (project_id);

-- ---------------------------------------------------------------------
-- New permissions. Global catalog (permission is not tenant-scoped, see
-- CR-016); every existing tenant's OWNER is backfilled here (OWNER holds
-- every permission by invariant). MANAGER gets full project management;
-- ACCOUNTANT gets view-only (needs project cost/profit visibility, same
-- reasoning as PRODUCT_VIEW_COST); STAFF gets project view only, no
-- material-cost visibility.
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('PROJECT_VIEW', 'View projects', 'View project details, status and profitability', 'PROJECT', 10),
 ('PROJECT_MANAGE', 'Manage projects', 'Create/edit projects, materials, expenses and payments', 'PROJECT', 20),
 ('PROJECT_MATERIAL_VIEW', 'View project materials', 'View materials used on a project and their cost', 'PROJECT', 30),
 ('PROJECT_MATERIAL_MANAGE', 'Manage project materials', 'Add, edit and remove materials on a project', 'PROJECT', 40);

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM role r CROSS JOIN permission p
WHERE r.role_code = 'OWNER' AND p.permission_code IN
    ('PROJECT_VIEW', 'PROJECT_MANAGE', 'PROJECT_MATERIAL_VIEW', 'PROJECT_MATERIAL_MANAGE');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM role r CROSS JOIN permission p
WHERE r.role_code = 'MANAGER' AND p.permission_code IN
    ('PROJECT_VIEW', 'PROJECT_MANAGE', 'PROJECT_MATERIAL_VIEW', 'PROJECT_MATERIAL_MANAGE');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM role r CROSS JOIN permission p
WHERE r.role_code = 'ACCOUNTANT' AND p.permission_code IN ('PROJECT_VIEW', 'PROJECT_MATERIAL_VIEW');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM role r CROSS JOIN permission p
WHERE r.role_code = 'STAFF' AND p.permission_code = 'PROJECT_VIEW';
