-- =====================================================================
-- MODULE 1 : AUTHENTICATION, USERS, ROLES, PERMISSIONS
-- Target engine: PostgreSQL 14+ (developed and tested against 16)
-- Single shop. No tenant_id anywhere.
--
-- Migrated from MySQL 8 under CR-014. Table and column names are unchanged;
-- only engine-specific syntax and two collation-driven guarantees differ.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Keeps `updated_at` current without the application having to remember.
-- Replaces MySQL's ON UPDATE CURRENT_TIMESTAMP, which has no PostgreSQL
-- equivalent. Only attached to tables whose entity does NOT extend
-- BaseEntity - everywhere else Spring Data JPA auditing owns the column,
-- and a trigger would fight it.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------
-- permission : first-class table so future modules add rows via their own
-- migration instead of editing a frozen Java constant list.
-- ---------------------------------------------------------------------
CREATE TABLE permission (
    permission_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    permission_code VARCHAR(60)  NOT NULL,
    permission_name VARCHAR(120) NOT NULL,
    description     VARCHAR(255),
    module_code     VARCHAR(30)  NOT NULL,
    display_order   INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(3),
    CONSTRAINT pk_permission PRIMARY KEY (permission_id),
    CONSTRAINT uk_permission_code UNIQUE (permission_code)
);

CREATE INDEX idx_permission_module ON permission (module_code, display_order);

CREATE TRIGGER trg_permission_updated_at
    BEFORE UPDATE ON permission
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE permission IS
    'Authoritative permission catalogue. PermissionCode.java only mirrors it for compile-time safety.';

-- ---------------------------------------------------------------------
-- role
-- ---------------------------------------------------------------------
CREATE TABLE role (
    role_id      BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    role_code    VARCHAR(30)  NOT NULL,
    role_name    VARCHAR(100) NOT NULL,
    description  VARCHAR(255),
    system_role  BOOLEAN      NOT NULL DEFAULT FALSE,
    status       VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at   TIMESTAMP(3) NOT NULL,
    created_by   BIGINT,
    updated_at   TIMESTAMP(3),
    updated_by   BIGINT,
    version      INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_role PRIMARY KEY (role_id),
    CONSTRAINT uk_role_code UNIQUE (role_code),
    CONSTRAINT ck_role_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- Case-insensitive uniqueness. MySQL got this free from utf8mb4_0900_ai_ci;
-- PostgreSQL compares case-sensitively, so without this "Staff" and "staff"
-- would both be accepted. See BUG-AUTH-009.
CREATE UNIQUE INDEX uk_role_name_lower ON role (lower(role_name));

CREATE TABLE role_permission (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)
        REFERENCES role (role_id) ON DELETE CASCADE,
    -- RESTRICT is deliberate: deleting a permission that roles still hold must fail.
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id)
        REFERENCES permission (permission_id) ON DELETE RESTRICT
);

CREATE INDEX idx_rp_permission ON role_permission (permission_id);

-- ---------------------------------------------------------------------
-- app_user : named app_user because USER is a reserved word in PostgreSQL
-- (and was in MySQL). Never hard-deleted; ERP records reference created_by
-- for the life of the business.
-- ---------------------------------------------------------------------
CREATE TABLE app_user (
    user_id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    role_id               BIGINT       NOT NULL,
    employee_code         VARCHAR(30),
    full_name             VARCHAR(200) NOT NULL,
    mobile_no             VARCHAR(15)  NOT NULL,
    email                 VARCHAR(255),
    password_hash         VARCHAR(255) NOT NULL,
    status                VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    must_change_password  BOOLEAN      NOT NULL DEFAULT FALSE,
    token_version         INTEGER      NOT NULL DEFAULT 0,
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP(3),
    last_login_at         TIMESTAMP(3),
    password_changed_at   TIMESTAMP(3),
    created_at            TIMESTAMP(3) NOT NULL,
    created_by            BIGINT,
    updated_at            TIMESTAMP(3),
    updated_by            BIGINT,
    deleted_at            TIMESTAMP(3),
    deleted_by            BIGINT,
    version               INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_app_user PRIMARY KEY (user_id),
    CONSTRAINT uk_user_mobile        UNIQUE (mobile_no),
    CONSTRAINT uk_user_employee_code UNIQUE (employee_code),
    CONSTRAINT fk_user_role FOREIGN KEY (role_id)
        REFERENCES role (role_id) ON DELETE RESTRICT,
    CONSTRAINT ck_user_status   CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED')),
    CONSTRAINT ck_user_attempts CHECK (failed_login_attempts >= 0),
    CONSTRAINT ck_user_tokenver CHECK (token_version >= 0)
);

-- Case-insensitive email uniqueness (BUG-AUTH-009). NULLs stay distinct, so
-- staff without an email address are unaffected.
CREATE UNIQUE INDEX uk_user_email_lower ON app_user (lower(email));

CREATE INDEX idx_user_role      ON app_user (role_id);
CREATE INDEX idx_user_status    ON app_user (status, deleted_at);
CREATE INDEX idx_user_full_name ON app_user (full_name);

-- Partial index: every list screen filters deleted rows out, and once former
-- employees accumulate this is far smaller than a full index.
CREATE INDEX idx_user_active ON app_user (user_id) WHERE deleted_at IS NULL;

COMMENT ON COLUMN app_user.token_version IS
    'Carried in every access token as the tv claim. Incrementing invalidates all outstanding tokens for this user.';

-- ---------------------------------------------------------------------
-- refresh_token : one row per session. Only SHA-256(token) is stored, so a
-- database dump yields nothing usable.
-- ---------------------------------------------------------------------
CREATE TABLE refresh_token (
    refresh_token_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id              BIGINT       NOT NULL,
    token_hash           CHAR(64)     NOT NULL,
    expires_at           TIMESTAMP(3) NOT NULL,
    revoked_at           TIMESTAMP(3),
    revoked_reason       VARCHAR(40),
    replaced_by_token_id BIGINT,
    ip_address           VARCHAR(45),
    user_agent           VARCHAR(255),
    last_used_at         TIMESTAMP(3),
    created_at           TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_refresh_token PRIMARY KEY (refresh_token_id),
    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id) ON DELETE CASCADE,
    -- Self-reference makes the rotation chain walkable during incident review.
    CONSTRAINT fk_refresh_token_replaced FOREIGN KEY (replaced_by_token_id)
        REFERENCES refresh_token (refresh_token_id) ON DELETE SET NULL,
    CONSTRAINT ck_refresh_token_reason CHECK (revoked_reason IS NULL OR revoked_reason IN
        ('ROTATED', 'LOGOUT', 'LOGOUT_ALL', 'REUSE_DETECTED', 'PASSWORD_CHANGED',
         'PASSWORD_RESET', 'USER_DEACTIVATED', 'ROLE_CHANGED', 'SESSION_REVOKED'))
);

CREATE INDEX idx_refresh_token_expiry ON refresh_token (expires_at);
-- Partial: the session list and revoke-all only ever look at live sessions.
CREATE INDEX idx_refresh_token_active ON refresh_token (user_id) WHERE revoked_at IS NULL;

-- ---------------------------------------------------------------------
-- password_reset_token : single-use, short-lived, stored hashed.
-- ---------------------------------------------------------------------
CREATE TABLE password_reset_token (
    reset_token_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id        BIGINT       NOT NULL,
    token_hash     CHAR(64)     NOT NULL,
    expires_at     TIMESTAMP(3) NOT NULL,
    used_at        TIMESTAMP(3),
    ip_address     VARCHAR(45),
    created_at     TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_password_reset_token PRIMARY KEY (reset_token_id),
    CONSTRAINT uk_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_reset_token_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id) ON DELETE CASCADE
);

CREATE INDEX idx_reset_token_expiry ON password_reset_token (expires_at);
CREATE INDEX idx_reset_token_unused ON password_reset_token (user_id) WHERE used_at IS NULL;

-- ---------------------------------------------------------------------
-- security_audit_log : SECURITY events only. Business transaction history
-- belongs to each ERP module's own tables.
-- No FK to app_user: the log must stay readable regardless of what happens
-- to the user row, and a failed login for an unknown identifier has no user
-- to point at.
-- ---------------------------------------------------------------------
CREATE TABLE security_audit_log (
    audit_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    action         VARCHAR(40)  NOT NULL,
    entity_type    VARCHAR(60),
    entity_id      BIGINT,
    user_id        BIGINT,
    full_name      VARCHAR(200),
    success        BOOLEAN      NOT NULL DEFAULT TRUE,
    failure_reason VARCHAR(255),
    ip_address     VARCHAR(45),
    user_agent     VARCHAR(255),
    request_id     VARCHAR(36),
    created_at     TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_security_audit_log PRIMARY KEY (audit_id)
);

CREATE INDEX idx_audit_user_date   ON security_audit_log (user_id, created_at DESC);
CREATE INDEX idx_audit_action_date ON security_audit_log (action, created_at DESC);
CREATE INDEX idx_audit_entity      ON security_audit_log (entity_type, entity_id);
CREATE INDEX idx_audit_created     ON security_audit_log (created_at DESC);
-- Partial: the security review screen almost always starts from failures.
CREATE INDEX idx_audit_failures    ON security_audit_log (created_at DESC) WHERE success = FALSE;

COMMENT ON TABLE security_audit_log IS
    'Never stores passwords, password hashes, raw refresh tokens, raw reset tokens or JWT material.';

-- =====================================================================
-- SEED : permissions.  Modules 2-12 add their own rows in their own migration.
-- =====================================================================
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('USER_VIEW',         'View users',            'See the user list and user details',      'AUTH',      10),
 ('USER_MANAGE',       'Manage users',          'Create, edit, deactivate users',          'AUTH',      20),
 ('ROLE_VIEW',         'View roles',            'See roles and their permissions',         'AUTH',      30),
 ('ROLE_MANAGE',       'Manage roles',          'Create and edit roles and permissions',   'AUTH',      40),
 ('AUDIT_VIEW',        'View security log',     'Read the security audit log',             'AUTH',      50),
 ('CUSTOMER_VIEW',     'View customers',        'See customers and balances',              'CUSTOMER',  10),
 ('CUSTOMER_MANAGE',   'Manage customers',      'Create and edit customers',               'CUSTOMER',  20),
 ('SUPPLIER_VIEW',     'View suppliers',        'See suppliers and balances',              'SUPPLIER',  10),
 ('SUPPLIER_MANAGE',   'Manage suppliers',      'Create and edit suppliers',               'SUPPLIER',  20),
 ('PRODUCT_VIEW',      'View products',         'Search products and see selling price',   'PRODUCT',   10),
 ('PRODUCT_MANAGE',    'Manage products',       'Create and edit products and variants',   'PRODUCT',   20),
 ('PRODUCT_VIEW_COST', 'View product cost',     'See purchase cost and margin',            'PRODUCT',   30),
 ('PRODUCT_VIEW_STOCK','View product stock',    'See stock on hand',                       'PRODUCT',   40),
 ('PURCHASE_VIEW',     'View purchases',        'See purchase orders and bills',           'PURCHASE',  10),
 ('PURCHASE_MANAGE',   'Manage purchases',      'Create and edit purchase documents',      'PURCHASE',  20),
 ('QUOTATION_VIEW',    'View quotations',       'See quotations',                          'SALES',     10),
 ('QUOTATION_MANAGE',  'Manage quotations',     'Create and edit quotations',              'SALES',     20),
 ('INVOICE_VIEW',      'View invoices',         'See sales invoices',                      'SALES',     30),
 ('INVOICE_CREATE',    'Create invoices',       'Raise sales invoices',                    'SALES',     40),
 ('INVOICE_CANCEL',    'Cancel invoices',       'Cancel a posted invoice',                 'SALES',     50),
 ('INVOICE_DISCOUNT_OVERRIDE', 'Override discount', 'Exceed the standard discount limit',  'SALES',     60),
 ('INVENTORY_VIEW',    'View inventory',        'See stock and movements',                 'INVENTORY', 10),
 ('INVENTORY_ADJUST',  'Adjust inventory',      'Post stock adjustments',                  'INVENTORY', 20),
 ('PAYMENT_VIEW',      'View payments',         'See receipts and payments',               'PAYMENT',   10),
 ('PAYMENT_MANAGE',    'Manage payments',       'Record receipts and payments',            'PAYMENT',   20),
 ('EXPENSE_VIEW',      'View expenses',         'See expenses',                            'EXPENSE',   10),
 ('EXPENSE_MANAGE',    'Manage expenses',       'Record and edit expenses',                'EXPENSE',   20),
 ('REPORT_VIEW',       'View reports',          'Operational reports',                     'REPORT',    10),
 ('REPORT_FINANCIAL',  'View financial reports','Profit, loss and cash reports',           'REPORT',    20),
 ('SETTINGS_VIEW',     'View settings',         'See shop settings',                       'SETTINGS',  10),
 ('SETTINGS_MANAGE',   'Manage settings',       'Change shop settings',                    'SETTINGS',  20);

-- =====================================================================
-- SEED : roles
-- =====================================================================
INSERT INTO role (role_code, role_name, description, system_role, status, created_at) VALUES
 ('OWNER',      'Owner',      'Unrestricted access',                     TRUE, 'ACTIVE', CURRENT_TIMESTAMP),
 ('MANAGER',    'Manager',    'Day to day operations, sees cost',        TRUE, 'ACTIVE', CURRENT_TIMESTAMP),
 ('ACCOUNTANT', 'Accountant', 'Billing, payments and financial reports', TRUE, 'ACTIVE', CURRENT_TIMESTAMP),
 ('STAFF',      'Staff',      'Billing counter, no cost visibility',     TRUE, 'ACTIVE', CURRENT_TIMESTAMP);

-- OWNER holds every permission that exists.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r CROSS JOIN permission p
WHERE r.role_code = 'OWNER';

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN (
    'USER_VIEW', 'ROLE_VIEW',
    'CUSTOMER_VIEW', 'CUSTOMER_MANAGE', 'SUPPLIER_VIEW', 'SUPPLIER_MANAGE',
    'PRODUCT_VIEW', 'PRODUCT_MANAGE', 'PRODUCT_VIEW_COST', 'PRODUCT_VIEW_STOCK',
    'PURCHASE_VIEW', 'PURCHASE_MANAGE',
    'QUOTATION_VIEW', 'QUOTATION_MANAGE', 'INVOICE_VIEW', 'INVOICE_CREATE',
    'INVOICE_DISCOUNT_OVERRIDE',
    'INVENTORY_VIEW', 'INVENTORY_ADJUST',
    'PAYMENT_VIEW', 'PAYMENT_MANAGE', 'EXPENSE_VIEW', 'EXPENSE_MANAGE',
    'REPORT_VIEW', 'SETTINGS_VIEW')
WHERE r.role_code = 'MANAGER';

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN (
    'CUSTOMER_VIEW', 'CUSTOMER_MANAGE', 'SUPPLIER_VIEW',
    'PRODUCT_VIEW', 'PRODUCT_VIEW_COST', 'PRODUCT_VIEW_STOCK',
    'QUOTATION_VIEW', 'INVOICE_VIEW', 'INVOICE_CREATE',
    'PAYMENT_VIEW', 'PAYMENT_MANAGE', 'EXPENSE_VIEW', 'EXPENSE_MANAGE',
    'PURCHASE_VIEW', 'INVENTORY_VIEW',
    'REPORT_VIEW', 'REPORT_FINANCIAL')
WHERE r.role_code = 'ACCOUNTANT';

-- STAFF deliberately excludes PRODUCT_VIEW_COST. Counter staff must not see
-- purchase cost or margin. Enforced server-side, not by hiding a field in React.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN (
    'CUSTOMER_VIEW', 'CUSTOMER_MANAGE',
    'PRODUCT_VIEW', 'PRODUCT_VIEW_STOCK',
    'QUOTATION_VIEW', 'QUOTATION_MANAGE',
    'INVOICE_VIEW', 'INVOICE_CREATE',
    'PAYMENT_VIEW', 'INVENTORY_VIEW')
WHERE r.role_code = 'STAFF';
