-- =====================================================================
-- CR-032 : subscription-plan trial coupons. Distinct from the retail
-- `coupon` table (CR-028, discounts a customer's invoice) - this is the
-- shop's OWN plan being granted for free for a limited time, redeemed by
-- the OWNER in Shop Settings. Tenant-scoped like every coupon-shaped
-- table in this schema (CR-016): a code created in one shop can never be
-- redeemed by another. Purely additive - a new table and one nullable
-- column, so this ships with zero risk to any existing row.
-- =====================================================================

CREATE TABLE subscription_coupon (
    coupon_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id     BIGINT        NOT NULL,
    code          VARCHAR(30)   NOT NULL,
    description   VARCHAR(255),
    granted_tier  VARCHAR(10)   NOT NULL,
    -- How long the granted tier lasts once redeemed, starting from the
    -- moment of redemption (not from valid_from/valid_until below, which
    -- gate when the code itself can be *used*, same distinction the
    -- retail coupon table already makes).
    trial_days    INTEGER       NOT NULL,
    valid_from    DATE,
    valid_until   DATE,
    -- Null = unlimited redemptions of this same code.
    usage_limit   INTEGER,
    times_used    INTEGER       NOT NULL DEFAULT 0,
    status        VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP(3)  NOT NULL,
    created_by    BIGINT,
    updated_at    TIMESTAMP(3),
    updated_by    BIGINT,
    version       INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT pk_subscription_coupon PRIMARY KEY (coupon_id),
    CONSTRAINT fk_subscription_coupon_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT ck_subscription_coupon_tier CHECK (granted_tier IN ('FREE', 'PRO', 'MAX')),
    CONSTRAINT ck_subscription_coupon_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_subscription_coupon_trial_days CHECK (trial_days > 0)
);

CREATE UNIQUE INDEX uk_subscription_coupon_code ON subscription_coupon (tenant_id, upper(code));
CREATE INDEX idx_subscription_coupon_tenant ON subscription_coupon (tenant_id, status);

-- When set, subscription_tier was granted by a trial redemption and must
-- revert to FREE once this passes - checked lazily on the next read
-- (SubscriptionServiceImpl.currentTier()), not by a scheduled job. Null
-- means the current tier (whatever it is) is permanent, exactly the
-- existing self-serve-picker behaviour from CR-027, untouched.
ALTER TABLE tenant ADD COLUMN subscription_trial_expires_at TIMESTAMP(3);

-- ---------------------------------------------------------------------
-- Reuses SETTINGS_MANAGE rather than adding new permission codes -
-- that permission is already OWNER-only in practice (MANAGER holds
-- SETTINGS_VIEW but not SETTINGS_MANAGE, see TenantRegistrationServiceImpl),
-- which matches exactly how sensitive plan/billing management should be
-- scoped. No new permission rows needed.
-- ---------------------------------------------------------------------
