-- =====================================================================
-- PURCHASE MODULE + SUPPLIER BILL IMPORT (customer-requested file upload
-- feature). Purchase is a genuine prerequisite for Supplier Bill Import
-- (a purchase document becomes a real Purchase, never a disconnected
-- table) and for the future Supplier Payables work - both explicitly
-- deferred until Purchase exists, per CHANGE_REQUEST_REGISTRY.md.
-- =====================================================================

CREATE TABLE purchase (
    purchase_id          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id             BIGINT        NOT NULL,
    purchase_number       VARCHAR(30)   NOT NULL,
    supplier_id           BIGINT        NOT NULL,
    supplier_bill_number  VARCHAR(60),
    purchase_date         DATE          NOT NULL,
    subtotal_paise        BIGINT        NOT NULL,
    gst_amount_paise      BIGINT        NOT NULL,
    total_paise           BIGINT        NOT NULL,
    paid_paise            BIGINT        NOT NULL DEFAULT 0,
    balance_paise         BIGINT        NOT NULL,
    status                VARCHAR(20)   NOT NULL DEFAULT 'RECEIVED',
    remarks                VARCHAR(500),
    -- Source traceability (spec §46) - null for a manually-created purchase,
    -- set only when this row was produced by confirming a Supplier Bill
    -- Import. imported_by is who clicked Confirm Import, not who uploaded
    -- the file (always the same request in this version, kept separate in
    -- case a review step is added between upload and confirm later).
    imported_at            TIMESTAMP(3),
    imported_by            BIGINT,
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT pk_purchase PRIMARY KEY (purchase_id),
    CONSTRAINT fk_purchase_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_purchase_supplier FOREIGN KEY (supplier_id)
        REFERENCES supplier (supplier_id),
    CONSTRAINT uk_purchase_number UNIQUE (tenant_id, purchase_number),
    CONSTRAINT ck_purchase_status CHECK (
        status IN ('DRAFT', 'RECEIVED', 'PARTIALLY_PAID', 'PAID', 'CANCELLED'))
);

CREATE INDEX idx_purchase_tenant   ON purchase (tenant_id);
CREATE INDEX idx_purchase_supplier ON purchase (tenant_id, supplier_id);
-- Duplicate-bill detection (spec §14) - a lookup, not a unique constraint,
-- since the owner can deliberately "Continue anyway" on a real duplicate
-- (e.g. a genuine second bill that happens to share a number by coincidence).
CREATE INDEX idx_purchase_duplicate_check
    ON purchase (tenant_id, supplier_id, supplier_bill_number, purchase_date);

CREATE TABLE purchase_item (
    purchase_item_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    purchase_id            BIGINT        NOT NULL,
    product_id              BIGINT        NOT NULL,
    product_name_snapshot   VARCHAR(255)  NOT NULL,
    quantity                 DECIMAL(18,4) NOT NULL,
    unit                     VARCHAR(20)   NOT NULL,
    unit_price_paise         BIGINT        NOT NULL,
    gst_rate_percent         DECIMAL(5,2)  NOT NULL DEFAULT 0,
    line_subtotal_paise      BIGINT        NOT NULL,
    line_gst_paise           BIGINT        NOT NULL,
    line_total_paise         BIGINT        NOT NULL,
    CONSTRAINT pk_purchase_item PRIMARY KEY (purchase_item_id),
    CONSTRAINT fk_purchase_item_purchase FOREIGN KEY (purchase_id)
        REFERENCES purchase (purchase_id) ON DELETE CASCADE,
    CONSTRAINT fk_purchase_item_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT ck_purchase_item_quantity CHECK (quantity > 0)
);

CREATE INDEX idx_purchase_item_purchase ON purchase_item (purchase_id);
CREATE INDEX idx_purchase_item_product  ON purchase_item (product_id);

CREATE TABLE purchase_payment (
    purchase_payment_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id             BIGINT       NOT NULL,
    purchase_id           BIGINT       NOT NULL,
    amount_paise           BIGINT       NOT NULL,
    payment_method         VARCHAR(20)  NOT NULL,
    payment_date           TIMESTAMP(3) NOT NULL,
    notes                   VARCHAR(255),
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    CONSTRAINT pk_purchase_payment PRIMARY KEY (purchase_payment_id),
    CONSTRAINT fk_purchase_payment_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_purchase_payment_purchase FOREIGN KEY (purchase_id)
        REFERENCES purchase (purchase_id),
    CONSTRAINT ck_purchase_payment_amount CHECK (amount_paise > 0),
    CONSTRAINT ck_purchase_payment_method CHECK (
        payment_method IN ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER'))
);

CREATE INDEX idx_purchase_payment_tenant   ON purchase_payment (tenant_id);
CREATE INDEX idx_purchase_payment_purchase ON purchase_payment (purchase_id);

-- Raw uploaded supplier-bill file (spec §19) - same bytea-in-Postgres
-- pattern as tenant_logo/tenant_signature/user_avatar (CR-023), so backup/
-- restore stays exactly as simple as it already is. Only ever written once,
-- atomically with the purchase.confirm-import transaction - never before a
-- human has confirmed the preview (spec §45's "upload != insertion").
CREATE TABLE purchase_document (
    purchase_document_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id              BIGINT       NOT NULL,
    purchase_id             BIGINT       NOT NULL,
    original_filename        VARCHAR(255) NOT NULL,
    content_type              VARCHAR(100) NOT NULL,
    file_size                 INTEGER      NOT NULL,
    checksum_sha256            VARCHAR(64)  NOT NULL,
    file_data                  BYTEA        NOT NULL,
    source_row_count           INTEGER,
    uploaded_by                 BIGINT,
    uploaded_at                 TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_purchase_document PRIMARY KEY (purchase_document_id),
    CONSTRAINT fk_purchase_document_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_purchase_document_purchase FOREIGN KEY (purchase_id)
        REFERENCES purchase (purchase_id) ON DELETE CASCADE,
    -- 20MB - generous for a scanned bill image/PDF while still bounding a
    -- single bytea row to something Postgres and a normal HTTP upload both
    -- handle comfortably.
    CONSTRAINT ck_purchase_document_size CHECK (file_size > 0 AND file_size <= 20971520)
);

CREATE INDEX idx_purchase_document_tenant   ON purchase_document (tenant_id);
CREATE INDEX idx_purchase_document_purchase ON purchase_document (purchase_id);

-- Purchase receiving increases stock through the one sanctioned choke
-- point (StockService.applyMovement) - never a direct quantity_on_hand
-- mutation. Widening the existing CHECK rather than adding a parallel
-- table, so every existing stock-movement reader (Stock detail page,
-- low-stock alert) sees purchase receipts in the same ledger for free.
ALTER TABLE stock_movement DROP CONSTRAINT ck_stock_movement_type;
ALTER TABLE stock_movement ADD CONSTRAINT ck_stock_movement_type CHECK (
    movement_type IN ('INITIAL', 'ADJUSTMENT', 'SALE', 'SALE_REVERSAL', 'PURCHASE_RECEIPT', 'PURCHASE_RETURN'));
