-- =====================================================================
-- CR-036 : multiple bank accounts per shop, each with its own set of
-- uploaded QR codes (GPay/PhonePe/Bank app, owner-labelled), selectable
-- per invoice. Purely additive - the existing single-account fields on
-- `tenant` (bank_account_name/bank_account_no/bank_ifsc/bank_name/
-- upi_id) and the existing `tenant_upi_qr` table are untouched and stay
-- the fallback whenever an invoice has no account explicitly selected,
-- so every existing invoice/tenant keeps working with zero migration
-- risk. account_number is encrypted at rest the same way as Supplier's
-- (CR-018, BankAccountNumberConverter reused as-is) - a shop's own
-- receiving account deserves the same protection as a supplier's.
-- =====================================================================

CREATE TABLE tenant_bank_account (
    bank_account_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id              BIGINT        NOT NULL,
    label                   VARCHAR(100)  NOT NULL,
    bank_name               VARCHAR(200)  NOT NULL,
    account_holder_name     VARCHAR(200)  NOT NULL,
    -- AES-256-GCM ciphertext via BankAccountNumberConverter, not the raw
    -- number - column is wide enough to hold it, same as supplier.bank_account_no.
    account_number          VARCHAR(255)  NOT NULL,
    ifsc_code               VARCHAR(11)   NOT NULL,
    upi_id                  VARCHAR(100),
    -- No "is_" prefix (naming law). The one account an invoice picks when
    -- the owner hasn't explicitly chosen one in the wizard.
    default_account         BOOLEAN       NOT NULL DEFAULT FALSE,
    status                  VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at              TIMESTAMP(3)  NOT NULL,
    created_by              BIGINT,
    updated_at              TIMESTAMP(3),
    updated_by              BIGINT,

    CONSTRAINT pk_tenant_bank_account PRIMARY KEY (bank_account_id),
    CONSTRAINT fk_tenant_bank_account_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT ck_tenant_bank_account_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX idx_tenant_bank_account_tenant ON tenant_bank_account (tenant_id, status);

-- Every uploaded QR image belongs to exactly one bank account (an owner
-- labels "SBI QR"/"GPay" per account, not globally) - deleting the
-- account deletes its QR codes with it, both at the FK level and via
-- JPA orphanRemoval on the owning side.
CREATE TABLE tenant_bank_account_qr (
    qr_id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    bank_account_id  BIGINT        NOT NULL,
    label             VARCHAR(100)  NOT NULL,
    content_type      VARCHAR(50)   NOT NULL,
    file_size         INTEGER       NOT NULL,
    image_data        BYTEA         NOT NULL,
    created_at        TIMESTAMP(3)  NOT NULL,
    created_by        BIGINT,
    updated_at        TIMESTAMP(3),
    updated_by        BIGINT,

    CONSTRAINT pk_tenant_bank_account_qr PRIMARY KEY (qr_id),
    CONSTRAINT fk_tenant_bank_account_qr_account FOREIGN KEY (bank_account_id)
        REFERENCES tenant_bank_account (bank_account_id) ON DELETE CASCADE
);

CREATE INDEX idx_tenant_bank_account_qr_account ON tenant_bank_account_qr (bank_account_id);

-- Nullable, live-resolved at PDF-render time (same principle CR-018 used
-- for decrypt-on-demand) - never snapshotted onto the invoice row, same
-- as the existing single-account payment block already behaves (it has
-- always read the tenant's *current* bank fields on every render, not a
-- point-in-time copy). ON DELETE SET NULL: deleting a bank account or one
-- of its QR codes never breaks an already-issued invoice - its PDF just
-- falls back to the shop's default single-account fields on next render.
ALTER TABLE invoice ADD COLUMN bank_account_id BIGINT
    REFERENCES tenant_bank_account (bank_account_id) ON DELETE SET NULL;
ALTER TABLE invoice ADD COLUMN bank_account_qr_id BIGINT
    REFERENCES tenant_bank_account_qr (qr_id) ON DELETE SET NULL;

-- ---------------------------------------------------------------------
-- Reuses SETTINGS_VIEW/SETTINGS_MANAGE - a shop's own bank accounts are
-- shop settings, not a new sensitivity class needing its own permission
-- code (unlike Supplier's bank details, which are a THIRD PARTY's data
-- and need SUPPLIER_VIEW_BANK_ACCOUNT to gate other staff from snooping).
-- ---------------------------------------------------------------------
