-- =====================================================================
-- CR-036 phase 3 : a standalone shop-wide expense ledger (rent, salaries,
-- utilities, misc costs) - explicitly separate from `project_expense`
-- (CR-029), which stays exactly as it is, scoped to individual projects.
-- Category is a plain user-extensible table, not a Java enum - same
-- reasoning as `work_type` (CR-029): a shop's own vocabulary for what it
-- spends money on is never restricted to what shipped in the seed.
-- =====================================================================

CREATE TABLE expense_category (
    expense_category_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id             BIGINT        NOT NULL,
    name                   VARCHAR(100)  NOT NULL,
    description            VARCHAR(500),
    created_at             TIMESTAMP(3)  NOT NULL,
    created_by             BIGINT,
    updated_at             TIMESTAMP(3),
    updated_by             BIGINT,

    CONSTRAINT pk_expense_category PRIMARY KEY (expense_category_id),
    CONSTRAINT fk_expense_category_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id)
);

CREATE UNIQUE INDEX uk_expense_category_name ON expense_category (tenant_id, upper(name));

CREATE TABLE business_expense (
    business_expense_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id              BIGINT        NOT NULL,
    expense_date            DATE          NOT NULL,
    category_id             BIGINT        NOT NULL,
    -- Paise, never a floating point rupee value - same reasoning as every
    -- other money column in this schema.
    amount_paise             BIGINT        NOT NULL,
    payment_method           VARCHAR(20)   NOT NULL,
    notes                    VARCHAR(500),
    status                   VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at               TIMESTAMP(3)  NOT NULL,
    created_by               BIGINT,
    updated_at               TIMESTAMP(3),
    updated_by               BIGINT,

    CONSTRAINT pk_business_expense PRIMARY KEY (business_expense_id),
    CONSTRAINT fk_business_expense_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_business_expense_category FOREIGN KEY (category_id) REFERENCES expense_category (expense_category_id),
    CONSTRAINT ck_business_expense_payment_method CHECK (payment_method IN ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER')),
    CONSTRAINT ck_business_expense_status CHECK (status IN ('ACTIVE', 'CANCELLED')),
    CONSTRAINT ck_business_expense_amount CHECK (amount_paise > 0)
);

CREATE INDEX idx_business_expense_tenant_date ON business_expense (tenant_id, expense_date DESC);
CREATE INDEX idx_business_expense_category ON business_expense (category_id);

-- One optional receipt photo per expense - same 1:1 bytea pattern as
-- product_image/user_avatar/tenant_logo, never joined into the ledger's
-- own list/search read path.
CREATE TABLE expense_receipt (
    business_expense_id  BIGINT        NOT NULL,
    content_type            VARCHAR(50)   NOT NULL,
    file_size                INTEGER       NOT NULL,
    image_data               BYTEA         NOT NULL,
    updated_at                TIMESTAMP(3)  NOT NULL,

    CONSTRAINT pk_expense_receipt PRIMARY KEY (business_expense_id),
    CONSTRAINT fk_expense_receipt_expense FOREIGN KEY (business_expense_id)
        REFERENCES business_expense (business_expense_id) ON DELETE CASCADE
);

-- ---------------------------------------------------------------------
-- EXPENSE_VIEW/EXPENSE_MANAGE already existed in the permission catalogue
-- since V1, seeded speculatively for this module before it existed -
-- reused as-is, no new permission codes needed.
-- ---------------------------------------------------------------------
