-- =====================================================================
-- CR-036 phase 4 : Labour Monitor - a worker directory, simple daily
-- present/absent/half-day attendance marking, and wage tracking.
-- Deliberately separate from project_expense's LABOUR/EMPLOYEE categories
-- (CR-029), which stay exactly as they are as a manual entry option -
-- V18's own header comment already flagged "labour_team / labour_employee
-- / attendance" as future work when project_expense was first built.
-- Wages are never stored; they are computed live from
-- worker.daily_rate_paise x attendance ratio (1 / 0.5 / 0) so a later
-- rate change never silently rewrites history.
-- =====================================================================

CREATE TABLE worker (
    worker_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id      BIGINT        NOT NULL,
    name           VARCHAR(150)  NOT NULL,
    mobile_no      VARCHAR(15),
    role_title     VARCHAR(100),
    -- Paise, never a floating point rupee value - same reasoning as every
    -- other money column in this schema.
    daily_rate_paise BIGINT      NOT NULL,
    status         VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    created_at     TIMESTAMP(3)  NOT NULL,
    created_by     BIGINT,
    updated_at     TIMESTAMP(3),
    updated_by     BIGINT,

    CONSTRAINT pk_worker PRIMARY KEY (worker_id),
    CONSTRAINT fk_worker_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT ck_worker_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_worker_daily_rate CHECK (daily_rate_paise > 0)
);

CREATE INDEX idx_worker_tenant_status ON worker (tenant_id, status);

-- One row per worker per day. project_id is optional - attendance can be
-- marked with no project (general shop labour) or tied to one project for
-- cost attribution on the Project detail page.
CREATE TABLE worker_attendance (
    worker_attendance_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id              BIGINT        NOT NULL,
    worker_id               BIGINT        NOT NULL,
    attendance_date          DATE          NOT NULL,
    status                    VARCHAR(20)   NOT NULL,
    project_id                BIGINT,
    notes                      VARCHAR(500),
    created_at                 TIMESTAMP(3)  NOT NULL,
    created_by                 BIGINT,
    updated_at                 TIMESTAMP(3),
    updated_by                 BIGINT,

    CONSTRAINT pk_worker_attendance PRIMARY KEY (worker_attendance_id),
    CONSTRAINT fk_worker_attendance_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_worker_attendance_worker FOREIGN KEY (worker_id) REFERENCES worker (worker_id),
    CONSTRAINT fk_worker_attendance_project FOREIGN KEY (project_id) REFERENCES project (project_id) ON DELETE SET NULL,
    CONSTRAINT ck_worker_attendance_status CHECK (status IN ('PRESENT', 'ABSENT', 'HALF_DAY')),
    CONSTRAINT uk_worker_attendance_worker_date UNIQUE (tenant_id, worker_id, attendance_date)
);

CREATE INDEX idx_worker_attendance_tenant_date ON worker_attendance (tenant_id, attendance_date DESC);
CREATE INDEX idx_worker_attendance_project ON worker_attendance (project_id);

-- Payments made to a worker against wages earned - mirrors
-- project_payment/purchase_payment's shape exactly.
CREATE TABLE worker_payment (
    worker_payment_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id            BIGINT        NOT NULL,
    worker_id             BIGINT        NOT NULL,
    amount_paise           BIGINT        NOT NULL,
    payment_date            DATE          NOT NULL,
    payment_method           VARCHAR(20)   NOT NULL,
    notes                     VARCHAR(500),
    created_at                TIMESTAMP(3)  NOT NULL,
    created_by                BIGINT,
    updated_at                TIMESTAMP(3),
    updated_by                BIGINT,

    CONSTRAINT pk_worker_payment PRIMARY KEY (worker_payment_id),
    CONSTRAINT fk_worker_payment_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_worker_payment_worker FOREIGN KEY (worker_id) REFERENCES worker (worker_id),
    CONSTRAINT ck_worker_payment_method CHECK (payment_method IN ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER')),
    CONSTRAINT ck_worker_payment_amount CHECK (amount_paise > 0)
);

CREATE INDEX idx_worker_payment_worker ON worker_payment (worker_id);

-- ---------------------------------------------------------------------
-- Unlike Purchase/Expense, no LABOUR permission code was ever speculatively
-- seeded in V1 - this is the first phase of CR-036 that genuinely needs new
-- permission rows.
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('LABOUR_VIEW',   'View labour',   'See workers, attendance and wages',        'LABOUR', 10),
 ('LABOUR_MANAGE', 'Manage labour', 'Manage workers, mark attendance, pay wages', 'LABOUR', 20);

-- OWNER's V1 CROSS JOIN grant only ran once, against whatever permission
-- rows existed at that time - it does NOT retroactively pick up permission
-- codes added by a later migration. Every module added after V1 must grant
-- OWNER explicitly here too, exactly as V18 (project management) does.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('LABOUR_VIEW', 'LABOUR_MANAGE')
WHERE r.role_code = 'OWNER';

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('LABOUR_VIEW', 'LABOUR_MANAGE')
WHERE r.role_code = 'MANAGER';

-- ACCOUNTANT handles payroll payments the same way it handles EXPENSE/PAYMENT.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('LABOUR_VIEW', 'LABOUR_MANAGE')
WHERE r.role_code = 'ACCOUNTANT';

-- STAFF deliberately gets no LABOUR permission - daily wage rates are
-- cost-like data, same reasoning that excludes PRODUCT_VIEW_COST from STAFF.
