-- =====================================================================
-- CR-040 : a record of which legal document version each user accepted.
--
-- A dedicated table rather than columns on app_user, for three reasons the
-- column approach cannot serve:
--   1. Re-consent. When Terms 1.1 ships, the 1.0 acceptance must survive as
--      history - overwriting a column destroys the evidence that the user
--      ever agreed to the version that was current at the time.
--   2. Marketing consent is revocable. "Granted, then withdrawn on this
--      date" is two facts, not one boolean.
--   3. Consent types differ in shape and will grow.
--
-- APPEND-ONLY. Rows are never updated or deleted; the newest row per
-- (user_id, consent_type) is the current position. Withdrawing marketing
-- consent inserts a row with granted = FALSE.
--
-- Deliberately does NOT store IP address or user agent. Neither is needed to
-- answer "who accepted which version, when", and collecting personal data
-- that no requirement calls for is exactly what the privacy policy this
-- table exists to support tells users we do not do.
-- =====================================================================

CREATE TABLE user_consent (
    user_consent_id   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id         BIGINT        NOT NULL,
    user_id           BIGINT        NOT NULL,
    consent_type      VARCHAR(20)   NOT NULL,
    -- Null only for MARKETING, which is a preference rather than agreement
    -- to a published document.
    document_version  VARCHAR(20),
    granted           BOOLEAN       NOT NULL,
    recorded_at       TIMESTAMP(3)  NOT NULL,
    created_at        TIMESTAMP(3)  NOT NULL,
    created_by        BIGINT,
    updated_at        TIMESTAMP(3),
    updated_by        BIGINT,

    CONSTRAINT pk_user_consent PRIMARY KEY (user_consent_id),
    CONSTRAINT fk_user_consent_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_user_consent_user FOREIGN KEY (user_id) REFERENCES app_user (user_id),
    CONSTRAINT ck_user_consent_type CHECK (consent_type IN ('TERMS', 'PRIVACY', 'MARKETING')),
    -- A document-backed consent is meaningless without knowing which version
    -- was agreed to; MARKETING has no document, so it must not carry one.
    CONSTRAINT ck_user_consent_version CHECK (
        (consent_type = 'MARKETING' AND document_version IS NULL)
        OR (consent_type IN ('TERMS', 'PRIVACY') AND document_version IS NOT NULL)
    )
);

CREATE INDEX idx_user_consent_user_type ON user_consent (user_id, consent_type, recorded_at DESC);
CREATE INDEX idx_user_consent_tenant ON user_consent (tenant_id);

COMMENT ON TABLE user_consent IS
    'Append-only record of legal document acceptance. Newest row per (user_id, consent_type) is current. LEGAL REVIEW REQUIRED before relying on this as evidence of consent in any jurisdiction.';
