-- =====================================================================
-- CR-041 : Per-tenant document number allocator.
--
-- Every code generator in the codebase allocated its next number as
--   findHighestGeneratedCodeNumber(tenantId) + 1
-- - a read, then a write, with nothing holding the gap. Two concurrent
-- counter staff creating invoices in the same shop both read the same
-- MAX and both attempt the same number; the uk_invoice_number unique
-- constraint catches it, so no duplicate is ever stored, but the loser
-- gets a constraint violation surfacing as a 500 and their invoice is
-- lost. Ten call sites across nine document types had this shape.
--
-- This table replaces that with a row that is locked FOR UPDATE for the
-- duration of the caller's transaction. Allocation joins the caller's
-- transaction deliberately (rather than REQUIRES_NEW): a rolled-back
-- invoice must not burn a number, because GST requires an unbroken
-- consecutive serial. The cost is that document creation serialises per
-- tenant per type, which for a hardware shop counter is a handful of
-- concurrent writers and entirely acceptable.
--
-- Lock ordering: the sequence row is always taken FIRST, before stock
-- rows or coupon rows, in every caller. Consistent ordering is what
-- keeps this deadlock-free.
-- =====================================================================

CREATE TABLE document_sequence (
    document_sequence_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id            BIGINT       NOT NULL,
    doc_type             VARCHAR(20)  NOT NULL,
    -- The next number to hand out, not the last one issued. A fresh row
    -- starts at 1 so the first allocation returns 1.
    next_value           BIGINT       NOT NULL DEFAULT 1,
    created_at           TIMESTAMP(3) NOT NULL,
    created_by           BIGINT,
    updated_at           TIMESTAMP(3),
    updated_by           BIGINT,

    CONSTRAINT pk_document_sequence PRIMARY KEY (document_sequence_id),
    CONSTRAINT fk_document_sequence_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT uk_document_sequence UNIQUE (tenant_id, doc_type),
    CONSTRAINT ck_document_sequence_doc_type CHECK (doc_type IN (
        'CUSTOMER', 'SUPPLIER', 'PRODUCT', 'CATEGORY', 'BRAND',
        'INVOICE', 'QUOTATION', 'PURCHASE', 'PROJECT'
    )),
    CONSTRAINT ck_document_sequence_next_value CHECK (next_value >= 1)
);

-- =====================================================================
-- Backfill. Each seed takes MAX(existing generated number) + 1 so the
-- first allocation after this migration continues the tenant's existing
-- run rather than colliding with it. The regex guard mirrors the one in
-- each repository query exactly - manually typed codes that do not match
-- the generated shape were never part of the sequence and must not be
-- now, or a hand-entered "INV-999999" would strand the counter.
-- =====================================================================

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'CUSTOMER',
       COALESCE(MAX(CAST(SUBSTRING(customer_code FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM customer WHERE customer_code ~ '^CUS-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'SUPPLIER',
       COALESCE(MAX(CAST(SUBSTRING(supplier_code FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM supplier WHERE supplier_code ~ '^SUP-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'PRODUCT',
       COALESCE(MAX(CAST(SUBSTRING(product_code FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM product WHERE product_code ~ '^PRD-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'CATEGORY',
       COALESCE(MAX(CAST(SUBSTRING(category_code FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM category WHERE category_code ~ '^CAT-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'BRAND',
       COALESCE(MAX(CAST(SUBSTRING(brand_code FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM brand WHERE brand_code ~ '^BRD-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'INVOICE',
       COALESCE(MAX(CAST(SUBSTRING(invoice_number FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM invoice WHERE invoice_number ~ '^INV-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'QUOTATION',
       COALESCE(MAX(CAST(SUBSTRING(quotation_number FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM quotation WHERE quotation_number ~ '^QUO-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'PURCHASE',
       COALESCE(MAX(CAST(SUBSTRING(purchase_number FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM purchase WHERE purchase_number ~ '^PUR-[0-9]+$' GROUP BY tenant_id;

INSERT INTO document_sequence (tenant_id, doc_type, next_value, created_at)
SELECT tenant_id, 'PROJECT',
       COALESCE(MAX(CAST(SUBSTRING(project_number FROM 5) AS INTEGER)), 0) + 1,
       NOW()
FROM project WHERE project_number ~ '^PRJ-[0-9]+$' GROUP BY tenant_id;

CREATE INDEX idx_document_sequence_tenant ON document_sequence (tenant_id);
