-- =====================================================================
-- MODULE 2 : SUPPLIER
-- Target engine: PostgreSQL 14+
--
-- Depends on: Module 1 (app_user for created_by/updated_by attribution).
-- The SUPPLIER_VIEW and SUPPLIER_MANAGE permissions already exist - they
-- were seeded by V1 - so no permission insert is needed here.
-- =====================================================================

CREATE TABLE supplier (
    supplier_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    supplier_code   VARCHAR(30)  NOT NULL,
    supplier_name   VARCHAR(255) NOT NULL,
    contact_person  VARCHAR(200),
    mobile_no       VARCHAR(15)  NOT NULL,
    alternate_mobile_no VARCHAR(15),
    email           VARCHAR(255),
    gst_no          VARCHAR(15),
    pan_no          VARCHAR(10),

    address_line1   VARCHAR(255),
    address_line2   VARCHAR(255),
    city            VARCHAR(100),
    state_code      CHAR(2),
    pincode         CHAR(6),

    -- Payment terms in days. 0 means cash on delivery.
    payment_terms_days INTEGER   NOT NULL DEFAULT 0,
    -- Credit ceiling in paise. Integer arithmetic only: a rupee amount held as
    -- a floating point number accumulates error across a year of purchases.
    credit_limit_paise BIGINT    NOT NULL DEFAULT 0,

    bank_account_name   VARCHAR(200),
    bank_account_no     VARCHAR(30),
    bank_ifsc           VARCHAR(11),
    bank_name           VARCHAR(200),

    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    remarks         TEXT,

    created_at      TIMESTAMP(3) NOT NULL,
    created_by      BIGINT,
    updated_at      TIMESTAMP(3),
    updated_by      BIGINT,
    deleted_at      TIMESTAMP(3),
    deleted_by      BIGINT,
    version         INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT pk_supplier PRIMARY KEY (supplier_id),
    CONSTRAINT uk_supplier_code UNIQUE (supplier_code),
    CONSTRAINT ck_supplier_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'BLOCKED')),
    CONSTRAINT ck_supplier_terms  CHECK (payment_terms_days >= 0),
    CONSTRAINT ck_supplier_credit CHECK (credit_limit_paise >= 0),
    -- 15 characters: 2 state + 10 PAN + 1 entity + 1 'Z' + 1 checksum.
    CONSTRAINT ck_supplier_gst    CHECK (gst_no IS NULL OR gst_no ~ '^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z][0-9A-Z]Z[0-9A-Z]$'),
    CONSTRAINT ck_supplier_pan    CHECK (pan_no IS NULL OR pan_no ~ '^[A-Z]{5}[0-9]{4}[A-Z]$'),
    CONSTRAINT ck_supplier_mobile CHECK (mobile_no ~ '^[6-9][0-9]{9}$'),
    CONSTRAINT ck_supplier_pincode CHECK (pincode IS NULL OR pincode ~ '^[1-9][0-9]{5}$')
);

-- Case-insensitive uniqueness, the same lesson as BUG-AUTH-009. PostgreSQL
-- compares case-sensitively, so without these "ABC Traders" and "abc traders"
-- would both be accepted as distinct suppliers.
CREATE UNIQUE INDEX uk_supplier_name_lower ON supplier (lower(supplier_name))
    WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_supplier_gst_lower  ON supplier (upper(gst_no))
    WHERE gst_no IS NOT NULL AND deleted_at IS NULL;

CREATE INDEX idx_supplier_status   ON supplier (status, deleted_at);
CREATE INDEX idx_supplier_name     ON supplier (supplier_name);
CREATE INDEX idx_supplier_mobile   ON supplier (mobile_no);
CREATE INDEX idx_supplier_city     ON supplier (city);
-- Every list screen filters deleted rows out; a partial index stays small as
-- former suppliers accumulate.
CREATE INDEX idx_supplier_active   ON supplier (supplier_id) WHERE deleted_at IS NULL;

COMMENT ON TABLE supplier IS
    'Businesses the shop buys from. Never hard-deleted: purchase documents from Module 8 reference supplier_id permanently.';
COMMENT ON COLUMN supplier.credit_limit_paise IS
    'Integer paise, never a float. Rupee amounts in floating point accumulate error.';

-- ---------------------------------------------------------------------
-- supplier_contact : a supplier often has several people - the owner, the
-- sales contact, the delivery coordinator. Storing one name on the supplier
-- row forces staff to overwrite it, losing the others.
-- ---------------------------------------------------------------------
CREATE TABLE supplier_contact (
    supplier_contact_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    supplier_id         BIGINT       NOT NULL,
    contact_name        VARCHAR(200) NOT NULL,
    designation         VARCHAR(100),
    mobile_no           VARCHAR(15)  NOT NULL,
    email               VARCHAR(255),
    is_primary          BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at          TIMESTAMP(3) NOT NULL,
    created_by          BIGINT,
    updated_at          TIMESTAMP(3),
    updated_by          BIGINT,
    version             INTEGER      NOT NULL DEFAULT 0,

    CONSTRAINT pk_supplier_contact PRIMARY KEY (supplier_contact_id),
    CONSTRAINT fk_supplier_contact_supplier FOREIGN KEY (supplier_id)
        REFERENCES supplier (supplier_id) ON DELETE CASCADE,
    CONSTRAINT ck_supplier_contact_mobile CHECK (mobile_no ~ '^[6-9][0-9]{9}$')
);

CREATE INDEX idx_supplier_contact_supplier ON supplier_contact (supplier_id);
-- At most one primary contact per supplier, enforced by the database rather
-- than by hoping the service layer gets it right.
CREATE UNIQUE INDEX uk_supplier_contact_primary
    ON supplier_contact (supplier_id) WHERE is_primary = TRUE;
