-- =====================================================================
-- CR-051 : Idempotency for financial write operations.
--
-- Flagged as a gap during the offline-sync design discussion and never
-- built. Needed now because Sales Order -> Delivery Challan -> Invoice
-- conversion (this same change) adds three more "click convert" actions
-- that move stock or money - and a double-click, a timeout-triggered
-- retry, or a slow connection on a shop counter must never create the
-- action twice.
--
-- DESIGN: the caller generates a UUID once (client-side or server-side,
-- whichever is calling) and sends it as Idempotency-Key. The first
-- request to use that key executes normally and stores its response
-- here; every later request with the same key gets that stored response
-- back WITHOUT re-executing the operation. The uniqueness is enforced by
-- the database, not by an application-level check-then-insert, which is
-- exactly the race CR-041 already fixed once for document numbering.
--
-- Scoped by (tenant_id, idempotency_key) rather than idempotency_key
-- alone: two different shops choosing the same client-generated UUID
-- (vanishingly unlikely, but not impossible with a buggy client) must
-- never collide with each other.
--
-- request_hash guards against key reuse with a DIFFERENT payload - the
-- one case idempotency must actively reject rather than silently replay,
-- because replaying invoice A's response for a request that actually
-- describes invoice B would be silently wrong, not merely redundant.
-- =====================================================================

CREATE TABLE idempotency_record (
    idempotency_record_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id              BIGINT        NOT NULL,
    idempotency_key        VARCHAR(100)  NOT NULL,
    -- Which endpoint this key was used against, so the same key on two
    -- different operations (a client bug) is caught rather than silently
    -- returning the wrong endpoint's cached response.
    operation               VARCHAR(100)  NOT NULL,
    request_hash            VARCHAR(64)   NOT NULL,
    response_status         INT           NOT NULL,
    response_body           TEXT          NOT NULL,
    created_at              TIMESTAMP(3)  NOT NULL,

    CONSTRAINT pk_idempotency_record PRIMARY KEY (idempotency_record_id),
    CONSTRAINT fk_idempotency_record_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    -- THE constraint that makes this safe: a concurrent duplicate loses the
    -- race here, in the database, not in a Java if-statement with a window
    -- between the check and the insert.
    CONSTRAINT uk_idempotency_record UNIQUE (tenant_id, idempotency_key)
);

CREATE INDEX idx_idempotency_record_created ON idempotency_record (created_at);
