-- =====================================================================
-- CR-052 phase 1a : Sales Order - a confirmed customer order raised
-- before goods are dispatched or a GST invoice is issued. Sits between
-- Quotation (a price offer, CR-022) and Delivery Challan/Invoice (goods
-- actually moving) in the sales pipeline the Master Prompt asked for.
--
-- Modelled directly on quotation/quotation_item (V10, V31, V32, V33) in
-- its FINAL shape rather than replayed incrementally, since this table
-- has no history to preserve - same three-column discount shape
-- (type/percent/authoritative-paise), same per-line internal labour
-- margin, same percentage-only discount type (CR-050 already retired
-- AMOUNT, so it is never offered here).
--
-- Like Quotation (CR-022), a Sales Order never moves stock and posts
-- nothing on its own - it is a commitment, not a financial or
-- inventory record. Converting it does:
--   -> Delivery Challan   goods leave without a tax invoice yet
--   -> Invoice            skips the challan, bills directly
-- Exactly one of converted_delivery_challan_id / converted_invoice_id
-- is ever set, mirroring quotation.converted_invoice_id. A Sales Order
-- converts once, to exactly one of the two - splitting one order across
-- several challans/invoices is exactly the "lifecycle-state engine"
-- CLAUDE.md's proactive-scope section reserves for a future CR, not
-- silently built in here.
-- =====================================================================

CREATE TABLE sales_order (
    sales_order_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id             BIGINT        NOT NULL,
    sales_order_number     VARCHAR(30)   NOT NULL,
    customer_id              BIGINT        NOT NULL,
    order_date                DATE          NOT NULL,
    -- Informational only, unlike quotation.valid_until - nothing gates on it.
    expected_delivery_date     DATE,

    discount_type                VARCHAR(20)   NOT NULL DEFAULT 'NONE',
    discount_percent             DECIMAL(5,2)  NOT NULL DEFAULT 0,
    discount_paise                BIGINT        NOT NULL DEFAULT 0,

    subtotal_paise                 BIGINT        NOT NULL,
    gst_amount_paise                BIGINT        NOT NULL,
    total_paise                      BIGINT        NOT NULL,

    status                             VARCHAR(20)   NOT NULL DEFAULT 'DRAFT',
    remarks                             VARCHAR(500),

    converted_delivery_challan_id        BIGINT,
    converted_invoice_id                  BIGINT,

    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT pk_sales_order PRIMARY KEY (sales_order_id),
    CONSTRAINT fk_sales_order_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_sales_order_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT fk_sales_order_invoice FOREIGN KEY (converted_invoice_id)
        REFERENCES invoice (invoice_id),
    CONSTRAINT uk_sales_order_number UNIQUE (tenant_id, sales_order_number),
    CONSTRAINT ck_sales_order_status CHECK (
        status IN ('DRAFT', 'CONFIRMED', 'CONVERTED', 'CANCELLED')),
    CONSTRAINT ck_sales_order_discount_type CHECK (
        discount_type IN ('NONE', 'PERCENTAGE')),
    CONSTRAINT ck_sales_order_discount_percent CHECK (
        discount_percent >= 0 AND discount_percent <= 100),
    CONSTRAINT ck_sales_order_amounts CHECK (
        discount_paise >= 0 AND subtotal_paise >= 0
        AND gst_amount_paise >= 0 AND total_paise >= 0)
    -- fk_sales_order_delivery_challan is added by V36, once delivery_challan exists.
);

CREATE INDEX idx_sales_order_tenant   ON sales_order (tenant_id);
CREATE INDEX idx_sales_order_customer ON sales_order (customer_id);
CREATE INDEX idx_sales_order_status   ON sales_order (tenant_id, status);

CREATE TRIGGER trg_sales_order_updated_at
    BEFORE UPDATE ON sales_order
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE sales_order_item (
    sales_order_item_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    sales_order_id           BIGINT        NOT NULL,
    product_id                 BIGINT        NOT NULL,
    product_name_snapshot        VARCHAR(255)  NOT NULL,
    quantity                       DECIMAL(18,4) NOT NULL,
    unit                             VARCHAR(20)   NOT NULL,
    unit_price_paise                  BIGINT        NOT NULL,
    gst_rate_percent                   DECIMAL(5,2)  NOT NULL DEFAULT 0,

    discount_type                        VARCHAR(20)   NOT NULL DEFAULT 'NONE',
    discount_percent                      DECIMAL(5,2)  NOT NULL DEFAULT 0,
    discount_amount_paise                  BIGINT        NOT NULL DEFAULT 0,

    labour_percent                          DECIMAL(5,2)  NOT NULL DEFAULT 0,
    labour_amount_paise                       BIGINT        NOT NULL DEFAULT 0,

    line_subtotal_paise                        BIGINT        NOT NULL,
    line_gst_paise                              BIGINT        NOT NULL,
    line_total_paise                             BIGINT        NOT NULL,

    CONSTRAINT pk_sales_order_item PRIMARY KEY (sales_order_item_id),
    CONSTRAINT fk_sales_order_item_sales_order FOREIGN KEY (sales_order_id)
        REFERENCES sales_order (sales_order_id) ON DELETE CASCADE,
    CONSTRAINT fk_sales_order_item_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT ck_sales_order_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_sales_order_item_discount_type CHECK (
        discount_type IN ('NONE', 'PERCENTAGE')),
    CONSTRAINT ck_sales_order_item_discount_percent CHECK (
        discount_percent >= 0 AND discount_percent <= 100),
    CONSTRAINT ck_sales_order_item_labour_percent CHECK (
        labour_percent >= 0 AND labour_percent <= 100),
    CONSTRAINT ck_sales_order_item_amounts CHECK (
        unit_price_paise >= 0 AND discount_amount_paise >= 0
        AND labour_amount_paise >= 0 AND line_subtotal_paise >= 0
        AND line_gst_paise >= 0 AND line_total_paise >= 0)
);

CREATE INDEX idx_sales_order_item_sales_order ON sales_order_item (sales_order_id);
CREATE INDEX idx_sales_order_item_product     ON sales_order_item (product_id);

-- ---------------------------------------------------------------------
-- document_sequence (CR-041 / V29) - widen the doc_type domain up front
-- for all three CR-052 document types, so V36/V37 do not each need their
-- own DROP/ADD CONSTRAINT round trip.
-- ---------------------------------------------------------------------
ALTER TABLE document_sequence DROP CONSTRAINT ck_document_sequence_doc_type;
ALTER TABLE document_sequence ADD CONSTRAINT ck_document_sequence_doc_type CHECK (doc_type IN (
    'CUSTOMER', 'SUPPLIER', 'PRODUCT', 'CATEGORY', 'BRAND',
    'INVOICE', 'QUOTATION', 'PURCHASE', 'PROJECT',
    'SALES_ORDER', 'DELIVERY_CHALLAN', 'CREDIT_NOTE'
));

-- ---------------------------------------------------------------------
-- Permissions (mirrors V25's pattern exactly - see its header comment).
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('SALES_ORDER_VIEW',   'View sales orders',   'See confirmed customer orders',                 'SALES_ORDER', 10),
 ('SALES_ORDER_MANAGE', 'Manage sales orders', 'Create, edit and convert sales orders',          'SALES_ORDER', 20);

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('SALES_ORDER_VIEW', 'SALES_ORDER_MANAGE')
WHERE r.role_code = 'OWNER';

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('SALES_ORDER_VIEW', 'SALES_ORDER_MANAGE')
WHERE r.role_code = 'MANAGER';

-- ACCOUNTANT sees orders for billing context but does not raise them,
-- same reasoning as its QUOTATION_VIEW-without-MANAGE grant.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code = 'SALES_ORDER_VIEW'
WHERE r.role_code = 'ACCOUNTANT';

-- STAFF takes orders at the counter the same way it raises quotations
-- and invoices.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('SALES_ORDER_VIEW', 'SALES_ORDER_MANAGE')
WHERE r.role_code = 'STAFF';
