-- =====================================================================
-- CR-052 phase 1b : Delivery Challan - proof that goods left the shop
-- without (yet) raising a GST tax invoice, the "bill to follow" /
-- job-work movement document Indian hardware trade commonly uses.
--
-- Deliberately NOT a tax document: no GST split, no discount ladder, no
-- internal labour margin - items carry only product, quantity and an
-- informational value (qty x unit price at the time of dispatch), never
-- charged to the customer from this record. Pricing/discount is decided
-- once at the invoicing step, same as it always has been - see
-- DeliveryChallanServiceImpl's header comment.
--
-- Stock genuinely leaves when a challan is issued (MovementType.DELIVERY,
-- added below) - a challan is proof of physical movement, unlike a
-- Sales Order or Quotation which never move stock. Converting a challan
-- to an Invoice reverses that movement first (DELIVERY_REVERSAL) and lets
-- InvoiceServiceImpl.create() take it again as a normal SALE, so the
-- Invoice module needs no changes at all and the net stock effect is
-- still exactly one unit out - see DeliveryChallanServiceImpl.
--
-- status: ISSUED (default, stock has left) -> CONVERTED (billed) or
-- CANCELLED (goods returned/never left, stock restored). No DRAFT - a
-- challan that has not been issued does not need to exist yet, mirroring
-- Invoice and Purchase's simple create+cancel model rather than a
-- reservation/allocation workflow.
-- =====================================================================

CREATE TABLE delivery_challan (
    delivery_challan_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id                 BIGINT        NOT NULL,
    delivery_challan_number     VARCHAR(30)   NOT NULL,
    customer_id                    BIGINT        NOT NULL,
    challan_date                    DATE          NOT NULL,

    transport_mode                    VARCHAR(50),
    vehicle_number                      VARCHAR(20),
    delivery_address                      VARCHAR(500),

    -- Informational only - qty x unit price at dispatch time, never a tax total.
    total_value_paise                        BIGINT        NOT NULL,

    status                                     VARCHAR(20)   NOT NULL DEFAULT 'ISSUED',
    remarks                                     VARCHAR(500),

    -- Set when this challan was raised by converting a Sales Order (nullable - a
    -- challan can also be created standalone, with no order behind it).
    source_sales_order_id                        BIGINT,
    converted_invoice_id                          BIGINT,

    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT pk_delivery_challan PRIMARY KEY (delivery_challan_id),
    CONSTRAINT fk_delivery_challan_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_delivery_challan_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT fk_delivery_challan_sales_order FOREIGN KEY (source_sales_order_id)
        REFERENCES sales_order (sales_order_id),
    CONSTRAINT fk_delivery_challan_invoice FOREIGN KEY (converted_invoice_id)
        REFERENCES invoice (invoice_id),
    CONSTRAINT uk_delivery_challan_number UNIQUE (tenant_id, delivery_challan_number),
    CONSTRAINT ck_delivery_challan_status CHECK (
        status IN ('ISSUED', 'CONVERTED', 'CANCELLED')),
    CONSTRAINT ck_delivery_challan_total CHECK (total_value_paise >= 0)
);

CREATE INDEX idx_delivery_challan_tenant   ON delivery_challan (tenant_id);
CREATE INDEX idx_delivery_challan_customer ON delivery_challan (customer_id);
CREATE INDEX idx_delivery_challan_status   ON delivery_challan (tenant_id, status);
CREATE INDEX idx_delivery_challan_sales_order ON delivery_challan (source_sales_order_id);

CREATE TRIGGER trg_delivery_challan_updated_at
    BEFORE UPDATE ON delivery_challan
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE delivery_challan_item (
    delivery_challan_item_id  BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    delivery_challan_id         BIGINT        NOT NULL,
    product_id                     BIGINT        NOT NULL,
    product_name_snapshot            VARCHAR(255)  NOT NULL,
    quantity                           DECIMAL(18,4) NOT NULL,
    unit                                 VARCHAR(20)   NOT NULL,
    unit_price_paise                      BIGINT        NOT NULL,
    value_paise                            BIGINT        NOT NULL,

    CONSTRAINT pk_delivery_challan_item PRIMARY KEY (delivery_challan_item_id),
    CONSTRAINT fk_delivery_challan_item_challan FOREIGN KEY (delivery_challan_id)
        REFERENCES delivery_challan (delivery_challan_id) ON DELETE CASCADE,
    CONSTRAINT fk_delivery_challan_item_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT ck_delivery_challan_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_delivery_challan_item_amounts CHECK (
        unit_price_paise >= 0 AND value_paise >= 0)
);

CREATE INDEX idx_delivery_challan_item_challan ON delivery_challan_item (delivery_challan_id);
CREATE INDEX idx_delivery_challan_item_product ON delivery_challan_item (product_id);

-- sales_order.converted_delivery_challan_id, deferred from V35 since
-- delivery_challan did not exist yet.
ALTER TABLE sales_order
    ADD CONSTRAINT fk_sales_order_delivery_challan FOREIGN KEY (converted_delivery_challan_id)
        REFERENCES delivery_challan (delivery_challan_id);

-- ---------------------------------------------------------------------
-- stock_movement (V8/V21) - widen movement_type for goods leaving via a
-- challan rather than a sale, and its reversal at DC->Invoice conversion
-- (see this file's header comment for why the reversal exists at all).
-- ---------------------------------------------------------------------
ALTER TABLE stock_movement DROP CONSTRAINT ck_stock_movement_type;
ALTER TABLE stock_movement ADD CONSTRAINT ck_stock_movement_type CHECK (
    movement_type IN (
        'INITIAL', 'ADJUSTMENT', 'SALE', 'SALE_REVERSAL',
        'PURCHASE_RECEIPT', 'PURCHASE_RETURN',
        'DELIVERY', 'DELIVERY_REVERSAL'
    ));

-- ---------------------------------------------------------------------
-- Permissions (mirrors V35's pattern).
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('DELIVERY_CHALLAN_VIEW',   'View delivery challans',   'See goods dispatched without a tax invoice', 'DELIVERY_CHALLAN', 10),
 ('DELIVERY_CHALLAN_MANAGE', 'Manage delivery challans', 'Issue, convert and cancel delivery challans', 'DELIVERY_CHALLAN', 20);

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('DELIVERY_CHALLAN_VIEW', 'DELIVERY_CHALLAN_MANAGE')
WHERE r.role_code = 'OWNER';

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('DELIVERY_CHALLAN_VIEW', 'DELIVERY_CHALLAN_MANAGE')
WHERE r.role_code = 'MANAGER';

-- ACCOUNTANT reconciles challans against later invoices but does not
-- dispatch goods - same reasoning as its INVENTORY_VIEW-without-ADJUST grant.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code = 'DELIVERY_CHALLAN_VIEW'
WHERE r.role_code = 'ACCOUNTANT';

-- STAFF gets neither - dispatching goods is a warehouse/manager function,
-- not front-counter billing (see RoleGrantDriftTest.WITHHELD_FROM_STAFF).
