-- =====================================================================
-- CR-052 phase 1c : Credit Note - a GST-compliant record of goods
-- returned against an already-issued Invoice.
--
-- Deliberately NOT an edit of the original invoice. InvoiceServiceImpl's
-- own update() comment already states the rule this follows: "altering
-- figures the customer has already settled against is what credit and
-- debit notes are for." A tax invoice, once issued, is never rewritten
-- here - Invoice's own columns (subtotal_paise, gst_amount_paise,
-- total_paise, paid_paise, balance_paise) are untouched by this
-- migration and by CreditNoteServiceImpl. A Credit Note stands beside the
-- invoice as its own document; "what the customer still owes net of
-- returns" is a reporting-layer question left for a future CR rather than
-- solved by mutating the settled invoice - see CreditNoteServiceImpl's
-- header comment.
--
-- credit_note_item.invoice_item_id (NOT NULL) links each returned line to
-- the EXACT original invoice_item row, not to a product id. This is
-- deliberate: BUG-FE-021 was exactly this class of defect (a line keyed
-- on product id instead of its own row silently corrupted every other
-- line with the same product), and an invoice can legitimately carry the
-- same product on two lines (e.g. two different discounts negotiated in
-- one sale). Keying by invoice_item_id makes that ambiguity impossible
-- here from the start.
--
-- Quantity already credited against a given invoice_item_id (summed
-- across every non-cancelled credit note) is capped at that line's
-- original quantity by CreditNoteServiceImpl at creation time - not by a
-- CHECK constraint, since it is a cross-row aggregate a CHECK cannot see.
-- =====================================================================

CREATE TABLE credit_note (
    credit_note_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id             BIGINT        NOT NULL,
    credit_note_number     VARCHAR(30)   NOT NULL,
    invoice_id                BIGINT        NOT NULL,
    customer_id                 BIGINT        NOT NULL,
    credit_note_date             DATE          NOT NULL,
    reason                         VARCHAR(500)  NOT NULL,

    subtotal_paise                  BIGINT        NOT NULL,
    gst_amount_paise                 BIGINT        NOT NULL,
    total_paise                       BIGINT        NOT NULL,

    status                              VARCHAR(20)   NOT NULL DEFAULT 'ISSUED',
    remarks                              VARCHAR(500),

    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,

    CONSTRAINT pk_credit_note PRIMARY KEY (credit_note_id),
    CONSTRAINT fk_credit_note_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_credit_note_invoice FOREIGN KEY (invoice_id)
        REFERENCES invoice (invoice_id),
    CONSTRAINT fk_credit_note_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT uk_credit_note_number UNIQUE (tenant_id, credit_note_number),
    CONSTRAINT ck_credit_note_status CHECK (status IN ('ISSUED', 'CANCELLED')),
    CONSTRAINT ck_credit_note_amounts CHECK (
        subtotal_paise >= 0 AND gst_amount_paise >= 0 AND total_paise >= 0)
);

CREATE INDEX idx_credit_note_tenant  ON credit_note (tenant_id);
CREATE INDEX idx_credit_note_invoice ON credit_note (invoice_id);
CREATE INDEX idx_credit_note_status  ON credit_note (tenant_id, status);

CREATE TRIGGER trg_credit_note_updated_at
    BEFORE UPDATE ON credit_note
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE credit_note_item (
    credit_note_item_id   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    credit_note_id           BIGINT        NOT NULL,
    invoice_item_id             BIGINT        NOT NULL,
    product_id                    BIGINT        NOT NULL,
    product_name_snapshot           VARCHAR(255)  NOT NULL,
    quantity                          DECIMAL(18,4) NOT NULL,
    unit                                VARCHAR(20)   NOT NULL,
    -- The effective per-unit rate credited (the original line's taxable
    -- value divided across its quantity), not the invoice's gross price -
    -- see CreditNoteServiceImpl.buildLine().
    unit_price_paise                     BIGINT        NOT NULL,
    gst_rate_percent                       DECIMAL(5,2)  NOT NULL DEFAULT 0,
    line_subtotal_paise                     BIGINT        NOT NULL,
    line_gst_paise                           BIGINT        NOT NULL,
    line_total_paise                          BIGINT        NOT NULL,

    CONSTRAINT pk_credit_note_item PRIMARY KEY (credit_note_item_id),
    CONSTRAINT fk_credit_note_item_credit_note FOREIGN KEY (credit_note_id)
        REFERENCES credit_note (credit_note_id) ON DELETE CASCADE,
    CONSTRAINT fk_credit_note_item_invoice_item FOREIGN KEY (invoice_item_id)
        REFERENCES invoice_item (invoice_item_id),
    CONSTRAINT fk_credit_note_item_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT ck_credit_note_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_credit_note_item_amounts CHECK (
        unit_price_paise >= 0 AND line_subtotal_paise >= 0
        AND line_gst_paise >= 0 AND line_total_paise >= 0)
);

CREATE INDEX idx_credit_note_item_credit_note  ON credit_note_item (credit_note_id);
-- Read on every create() to sum already-credited quantity for a line -
-- see this file's header comment.
CREATE INDEX idx_credit_note_item_invoice_item ON credit_note_item (invoice_item_id);

-- ---------------------------------------------------------------------
-- stock_movement (V8/V21/V36) - goods physically coming back into the
-- shop, and the reversal of that when a credit note is itself cancelled.
-- ---------------------------------------------------------------------
ALTER TABLE stock_movement DROP CONSTRAINT ck_stock_movement_type;
ALTER TABLE stock_movement ADD CONSTRAINT ck_stock_movement_type CHECK (
    movement_type IN (
        'INITIAL', 'ADJUSTMENT', 'SALE', 'SALE_REVERSAL',
        'PURCHASE_RECEIPT', 'PURCHASE_RETURN',
        'DELIVERY', 'DELIVERY_REVERSAL',
        'SALES_RETURN', 'SALES_RETURN_REVERSAL'
    ));

-- ---------------------------------------------------------------------
-- Permissions (mirrors V35/V36's pattern).
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('CREDIT_NOTE_VIEW',   'View credit notes',   'See goods returned against an invoice',    'CREDIT_NOTE', 10),
 ('CREDIT_NOTE_MANAGE', 'Manage credit notes', 'Issue and cancel credit notes for returns', 'CREDIT_NOTE', 20);

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('CREDIT_NOTE_VIEW', 'CREDIT_NOTE_MANAGE')
WHERE r.role_code = 'OWNER';

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('CREDIT_NOTE_VIEW', 'CREDIT_NOTE_MANAGE')
WHERE r.role_code = 'MANAGER';

-- A credit note is a financial document, same footing as INVOICE_CREATE.
INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('CREDIT_NOTE_VIEW', 'CREDIT_NOTE_MANAGE')
WHERE r.role_code = 'ACCOUNTANT';

-- STAFF gets neither - issuing a return/credit is not front-counter
-- authority (see RoleGrantDriftTest.WITHHELD_FROM_STAFF).
