-- =====================================================================
-- COMMON : BUSINESS ACTIVITY LOG  (CR-015)
--
-- Separate from security_audit_log, which stays for logins, token misuse
-- and password/role changes. This table records what changed in the
-- business data: which supplier, which field, from what to what.
--
-- Used by every module from Module 2 onwards.
-- =====================================================================

CREATE TABLE activity_log (
    activity_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY,

    -- Which module the change belongs to: SUPPLIER, CUSTOMER, PRODUCT ...
    module_code  VARCHAR(30)  NOT NULL,
    -- The record type inside that module, e.g. SUPPLIER or SUPPLIER_CONTACT.
    entity_type  VARCHAR(60)  NOT NULL,
    entity_id    BIGINT,
    -- A human-readable label, snapshotted. The record may later be renamed
    -- or deactivated, and the log must still say what it referred to.
    entity_label VARCHAR(255),

    action       VARCHAR(30)  NOT NULL,

    -- Changed fields only, not the whole row. jsonb because the shape differs
    -- per module and a fixed column list would not fit them all.
    old_values   JSONB,
    new_values   JSONB,

    user_id      BIGINT,
    full_name    VARCHAR(200),
    role_code    VARCHAR(30),
    ip_address   VARCHAR(45),
    request_id   VARCHAR(36),
    remarks      VARCHAR(500),

    created_at   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_activity_log PRIMARY KEY (activity_id),
    CONSTRAINT ck_activity_action CHECK (action IN
        ('CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'STATUS_CHANGE',
         'IMPORT', 'EXPORT', 'PRINT', 'APPROVE', 'REJECT', 'CANCEL'))
);

CREATE INDEX idx_activity_entity  ON activity_log (entity_type, entity_id, created_at DESC);
CREATE INDEX idx_activity_module  ON activity_log (module_code, created_at DESC);
CREATE INDEX idx_activity_user    ON activity_log (user_id, created_at DESC);
CREATE INDEX idx_activity_created ON activity_log (created_at DESC);

COMMENT ON TABLE activity_log IS
    'Business record history (CR-015). Security events live in security_audit_log. Never deleted by default.';
COMMENT ON COLUMN activity_log.old_values IS
    'Changed fields only. Never stores passwords, tokens or bank account numbers.';
