-- =====================================================================
-- CR-056 : Tenant-owned WhatsApp Business API integration.
--
-- One connection per tenant, holding THAT tenant's own Meta WhatsApp
-- Cloud API credentials - never a shared app-wide number. phone_number_id
-- is unique across the whole table (not just per tenant): it is also the
-- routing key an inbound webhook event uses to find which tenant a
-- message/status update belongs to (see WhatsAppWebhookController), so two
-- tenants can never legitimately share one.
--
-- access_token is encrypted at rest via WhatsAppAccessTokenConverter,
-- reusing FieldEncryptor (CR-018) rather than inventing a second scheme.
--
-- Phase 1 uses manual credential entry (the tenant pastes a token they
-- already obtained from their own Meta Business Manager/WABA) rather than
-- Meta's Embedded Signup OAuth flow, which needs a Meta Tech Provider app
-- with Business verification and App Review already granted - not
-- something this environment has. The table shape does not change when
-- Embedded Signup is added later; only how access_token/phone_number_id
-- get populated changes.
-- =====================================================================

CREATE TABLE tenant_whatsapp_connection (
    whatsapp_connection_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id                BIGINT       NOT NULL,
    business_account_id       VARCHAR(50)  NOT NULL,
    phone_number_id             VARCHAR(50)  NOT NULL,
    display_phone_number          VARCHAR(20)  NOT NULL,
    business_name                    VARCHAR(200) NOT NULL,
    -- Encrypted (ENC: prefix) when APP_ENCRYPTION_KEY is configured, plaintext otherwise - see FieldEncryptor.
    access_token                       VARCHAR(2000),
    connection_status                    VARCHAR(20)  NOT NULL DEFAULT 'CONNECTED',
    connected_at                            TIMESTAMP(3) NOT NULL,
    last_verified_at                          TIMESTAMP(3),
    disconnected_at                             TIMESTAMP(3),

    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,

    CONSTRAINT pk_tenant_whatsapp_connection PRIMARY KEY (whatsapp_connection_id),
    CONSTRAINT fk_tenant_whatsapp_connection_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    -- One connection per tenant (phase 1 - see spec's own note that multiple
    -- numbers per tenant would need this relaxed deliberately, not by accident).
    CONSTRAINT uk_tenant_whatsapp_connection_tenant UNIQUE (tenant_id),
    CONSTRAINT uk_tenant_whatsapp_connection_phone_number_id UNIQUE (phone_number_id),
    CONSTRAINT ck_tenant_whatsapp_connection_status CHECK (
        connection_status IN ('CONNECTED', 'DISCONNECTED', 'NEEDS_ATTENTION'))
);

CREATE INDEX idx_tenant_whatsapp_connection_tenant ON tenant_whatsapp_connection (tenant_id);

CREATE TRIGGER trg_tenant_whatsapp_connection_updated_at
    BEFORE UPDATE ON tenant_whatsapp_connection
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- Customer WhatsApp consent (spec §16). mobile_no (already NOT NULL on
-- every customer) doubles as the WhatsApp destination number - the whole
-- codebase already sends WhatsApp/SMS to it (see NotificationServiceImpl),
-- so this does not introduce a second, redundant "whatsappNumber" column.
--
-- Defaults to true: every customer already receives transactional
-- WhatsApp messages today (invoice created, payment received) as a normal
-- part of the sale they are already in, not unsolicited marketing - Meta's
-- own policy distinguishes utility/transactional messages from marketing
-- ones. This column is what lets an owner turn that off for a specific
-- customer who objects, per the spec's "clear way to record/manage
-- consent" - it does not retroactively gate the transactional sends that
-- were already shipping before this CR.
-- ---------------------------------------------------------------------
ALTER TABLE customer ADD COLUMN whatsapp_opt_in BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE customer ADD COLUMN whatsapp_opt_in_at TIMESTAMP(3);

-- ---------------------------------------------------------------------
-- notification_log.status (V14) gains DELIVERED/READ - set only by a real
-- inbound Meta webhook event (WhatsAppWebhookController), never assumed
-- or faked client-side. See spec §13's own "never fake DELIVERED or READ".
-- ---------------------------------------------------------------------
ALTER TABLE notification_log DROP CONSTRAINT ck_notification_log_status;
ALTER TABLE notification_log ADD CONSTRAINT ck_notification_log_status CHECK (
    status IN ('SENT', 'LOGGED_ONLY', 'FAILED', 'DELIVERED', 'READ'));
