-- =====================================================================
-- CR-078 : one-time codes sent by email, and whether an address was ever
-- proven to belong to the person using it.
--
-- One table for every purpose a code serves - verifying an email at shop
-- registration, the second factor for a user with no authenticator app,
-- a password reset, and a step-up before a sensitive action - rather than
-- four tables with the same seven columns. `purpose` is what keeps them
-- apart: a code issued for a password reset can never satisfy a login.
--
-- user_id is NULLABLE, and that is the point: at registration the code is
-- sent before the account exists, so there is no user to point at yet.
-- Every other purpose sets it.
--
-- code_hash is SHA-256 of the six digits, the same treatment backup codes
-- get - VARCHAR, not CHAR, for the reason V4 records: Hibernate validates
-- bpchar as a type mismatch against a String column. Be honest about what that buys: a six-digit space is a million
-- values, and anyone holding a database dump can hash all of them in well
-- under a second. The hash keeps a live code out of casual reads of the
-- table and out of logs; the actual controls are the ten-minute expiry and
-- the five-attempt cap on `attempts`, both enforced in EmailOtpServiceImpl.
-- =====================================================================

CREATE TABLE email_otp (
    email_otp_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id       BIGINT,
    email         VARCHAR(255) NOT NULL,
    purpose       VARCHAR(20)  NOT NULL,
    code_hash     VARCHAR(64)  NOT NULL,
    attempts      INTEGER      NOT NULL DEFAULT 0,
    expires_at    TIMESTAMP(3) NOT NULL,
    consumed_at   TIMESTAMP(3),
    ip_address    VARCHAR(45),
    created_at    TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_email_otp PRIMARY KEY (email_otp_id),
    CONSTRAINT fk_email_otp_user FOREIGN KEY (user_id)
        REFERENCES app_user (user_id) ON DELETE CASCADE,
    CONSTRAINT chk_email_otp_purpose
        CHECK (purpose IN ('EMAIL_VERIFY', 'LOGIN', 'PASSWORD_RESET', 'STEP_UP'))
);

-- The one query that matters: "the newest live code for this address and
-- purpose". Email is stored lower-cased by the service, so no functional
-- index is needed here.
CREATE INDEX idx_email_otp_lookup ON email_otp (email, purpose, created_at DESC);
CREATE INDEX idx_email_otp_expiry ON email_otp (expires_at);

-- Set the first time a code sent to this address is successfully entered,
-- for any purpose - a password reset proves ownership as well as a
-- registration does. Cleared when the address changes. Nullable because
-- every account that exists today predates the question.
ALTER TABLE app_user ADD COLUMN email_verified_at TIMESTAMP(3);
