-- =====================================================================
-- CR-092 : PREMIUM growth pack
--   1. Multi-branch: branch master (one MAIN per tenant, backfilled),
--      branch attribution on invoice / purchase / stock_movement /
--      app_user, a per-branch stock breakdown, stock transfers.
--   2. Tenant backups: history + stored snapshots.
--   3. Permissions for the above.
-- Target engine: PostgreSQL 16.
--
-- Stock authority is unchanged: `stock.quantity_on_hand` (per tenant) is
-- still the one figure every availability check reads. `branch_stock` is a
-- measured breakdown of it, maintained by the same movement code, so the
-- branches of a shop always sum to the shop. It is never invented.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1a. Branch master
-- ---------------------------------------------------------------------
CREATE TABLE branch (
    branch_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id       BIGINT       NOT NULL,
    branch_code     VARCHAR(20)  NOT NULL,
    branch_name     VARCHAR(150) NOT NULL,
    address_line1   VARCHAR(255),
    city            VARCHAR(100),
    state_code      VARCHAR(2),
    pincode         VARCHAR(6),
    phone           VARCHAR(15),
    is_main         BOOLEAN      NOT NULL DEFAULT FALSE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMP(3) NOT NULL,
    created_by      BIGINT,
    updated_at      TIMESTAMP(3),
    updated_by      BIGINT,
    version         INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_branch PRIMARY KEY (branch_id),
    CONSTRAINT fk_branch_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT uq_branch_code UNIQUE (tenant_id, branch_code),
    CONSTRAINT ck_branch_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);
-- Exactly one main branch per shop - the one every existing row belongs to.
CREATE UNIQUE INDEX uq_branch_main_per_tenant ON branch (tenant_id) WHERE is_main = TRUE;
CREATE INDEX idx_branch_tenant ON branch (tenant_id, status);

INSERT INTO branch (tenant_id, branch_code, branch_name, address_line1, city, state_code, pincode, phone, is_main, status, created_at)
SELECT t.tenant_id, 'MAIN', t.name, t.address_line1, t.city, t.state_code, t.pincode, t.phone, TRUE, 'ACTIVE', now()
FROM tenant t;

-- ---------------------------------------------------------------------
-- 1b. Attribution. Nullable on app_user (null = not restricted to one
--     branch - the owner). NOT NULL on documents after the backfill.
-- ---------------------------------------------------------------------
ALTER TABLE app_user ADD COLUMN branch_id BIGINT;
ALTER TABLE app_user ADD CONSTRAINT fk_app_user_branch FOREIGN KEY (branch_id) REFERENCES branch (branch_id);

ALTER TABLE invoice ADD COLUMN branch_id BIGINT;
UPDATE invoice i SET branch_id = b.branch_id FROM branch b WHERE b.tenant_id = i.tenant_id AND b.is_main;
ALTER TABLE invoice ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE invoice ADD CONSTRAINT fk_invoice_branch FOREIGN KEY (branch_id) REFERENCES branch (branch_id);
CREATE INDEX idx_invoice_branch ON invoice (tenant_id, branch_id, invoice_date);

ALTER TABLE purchase ADD COLUMN branch_id BIGINT;
UPDATE purchase p SET branch_id = b.branch_id FROM branch b WHERE b.tenant_id = p.tenant_id AND b.is_main;
ALTER TABLE purchase ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE purchase ADD CONSTRAINT fk_purchase_branch FOREIGN KEY (branch_id) REFERENCES branch (branch_id);
CREATE INDEX idx_purchase_branch ON purchase (tenant_id, branch_id, purchase_date);

ALTER TABLE stock_movement ADD COLUMN branch_id BIGINT;
UPDATE stock_movement m SET branch_id = b.branch_id FROM branch b WHERE b.tenant_id = m.tenant_id AND b.is_main;
ALTER TABLE stock_movement ALTER COLUMN branch_id SET NOT NULL;
ALTER TABLE stock_movement ADD CONSTRAINT fk_stock_movement_branch FOREIGN KEY (branch_id) REFERENCES branch (branch_id);

ALTER TABLE stock_movement DROP CONSTRAINT ck_stock_movement_type;
ALTER TABLE stock_movement ADD CONSTRAINT ck_stock_movement_type CHECK (
    movement_type IN (
        'INITIAL', 'ADJUSTMENT', 'SALE', 'SALE_REVERSAL',
        'PURCHASE_RECEIPT', 'PURCHASE_RETURN',
        'DELIVERY', 'DELIVERY_REVERSAL',
        'SALES_RETURN', 'SALES_RETURN_REVERSAL',
        'PROJECT_CONSUMPTION', 'PROJECT_CONSUMPTION_REVERSAL',
        'STOCK_TRANSFER_OUT', 'STOCK_TRANSFER_IN'
    ));

-- ---------------------------------------------------------------------
-- 1c. Per-branch stock breakdown. Sums to stock.quantity_on_hand for the
--     tenant; may go negative for a branch that sold goods it never
--     received through a purchase or transfer - shown as such, never hidden.
-- ---------------------------------------------------------------------
CREATE TABLE branch_stock (
    branch_stock_id   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id         BIGINT        NOT NULL,
    branch_id         BIGINT        NOT NULL,
    product_id        BIGINT        NOT NULL,
    quantity_on_hand  DECIMAL(18,4) NOT NULL DEFAULT 0,
    updated_at        TIMESTAMP(3)  NOT NULL DEFAULT now(),
    CONSTRAINT pk_branch_stock PRIMARY KEY (branch_stock_id),
    CONSTRAINT fk_branch_stock_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_branch_stock_branch FOREIGN KEY (branch_id) REFERENCES branch (branch_id),
    CONSTRAINT fk_branch_stock_product FOREIGN KEY (product_id) REFERENCES product (product_id),
    CONSTRAINT uq_branch_stock UNIQUE (branch_id, product_id)
);
CREATE INDEX idx_branch_stock_tenant_product ON branch_stock (tenant_id, product_id);

INSERT INTO branch_stock (tenant_id, branch_id, product_id, quantity_on_hand, updated_at)
SELECT s.tenant_id, b.branch_id, s.product_id, s.quantity_on_hand, now()
FROM stock s JOIN branch b ON b.tenant_id = s.tenant_id AND b.is_main;

-- ---------------------------------------------------------------------
-- 1d. Stock transfers - a document, with one OUT and one IN movement per
--     line. Net tenant stock is unchanged by a transfer.
-- ---------------------------------------------------------------------
CREATE TABLE stock_transfer (
    stock_transfer_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id          BIGINT       NOT NULL,
    transfer_number    VARCHAR(30)  NOT NULL,
    from_branch_id     BIGINT       NOT NULL,
    to_branch_id       BIGINT       NOT NULL,
    status             VARCHAR(20)  NOT NULL DEFAULT 'COMPLETED',
    notes              VARCHAR(500),
    created_at         TIMESTAMP(3) NOT NULL,
    created_by         BIGINT,
    CONSTRAINT pk_stock_transfer PRIMARY KEY (stock_transfer_id),
    CONSTRAINT fk_stock_transfer_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT fk_stock_transfer_from FOREIGN KEY (from_branch_id) REFERENCES branch (branch_id),
    CONSTRAINT fk_stock_transfer_to FOREIGN KEY (to_branch_id) REFERENCES branch (branch_id),
    CONSTRAINT uq_stock_transfer_number UNIQUE (tenant_id, transfer_number),
    CONSTRAINT ck_stock_transfer_branches CHECK (from_branch_id <> to_branch_id),
    CONSTRAINT ck_stock_transfer_status CHECK (status IN ('COMPLETED'))
);
CREATE INDEX idx_stock_transfer_tenant ON stock_transfer (tenant_id, created_at DESC);

CREATE TABLE stock_transfer_item (
    stock_transfer_item_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    stock_transfer_id      BIGINT        NOT NULL,
    product_id             BIGINT        NOT NULL,
    product_name_snapshot  VARCHAR(255)  NOT NULL,
    quantity               DECIMAL(18,4) NOT NULL,
    CONSTRAINT pk_stock_transfer_item PRIMARY KEY (stock_transfer_item_id),
    CONSTRAINT fk_stock_transfer_item_transfer FOREIGN KEY (stock_transfer_id) REFERENCES stock_transfer (stock_transfer_id) ON DELETE CASCADE,
    CONSTRAINT fk_stock_transfer_item_product FOREIGN KEY (product_id) REFERENCES product (product_id),
    CONSTRAINT ck_stock_transfer_item_qty CHECK (quantity > 0)
);

-- ---------------------------------------------------------------------
-- 2. Tenant backups. The snapshot bytes are kept on the row so a past
--    backup can be downloaded again; a nightly job prunes to the last 7.
-- ---------------------------------------------------------------------
CREATE TABLE tenant_backup (
    tenant_backup_id BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id        BIGINT       NOT NULL,
    format           VARCHAR(10)  NOT NULL,
    trigger_type     VARCHAR(20)  NOT NULL,
    status           VARCHAR(20)  NOT NULL,
    record_count     INTEGER,
    file_size_bytes  BIGINT,
    file_data        BYTEA,
    error_detail     VARCHAR(500),
    created_by       BIGINT,
    created_at       TIMESTAMP(3) NOT NULL,
    CONSTRAINT pk_tenant_backup PRIMARY KEY (tenant_backup_id),
    CONSTRAINT fk_tenant_backup_tenant FOREIGN KEY (tenant_id) REFERENCES tenant (tenant_id),
    CONSTRAINT ck_tenant_backup_format CHECK (format IN ('JSON', 'CSV')),
    CONSTRAINT ck_tenant_backup_trigger CHECK (trigger_type IN ('MANUAL', 'SCHEDULED')),
    CONSTRAINT ck_tenant_backup_status CHECK (status IN ('COMPLETED', 'FAILED'))
);
CREATE INDEX idx_tenant_backup_tenant ON tenant_backup (tenant_id, created_at DESC);

-- ---------------------------------------------------------------------
-- 3. Permissions. BRANCH_VIEW for every role (a branch name is printed
--    on documents); BRANCH_MANAGE and BACKUP_MANAGE owner-only;
--    STOCK_TRANSFER_MANAGE owner + manager. Insights reuse REPORT_VIEW.
-- ---------------------------------------------------------------------
INSERT INTO permission (permission_code, permission_name, description, module_code, display_order) VALUES
 ('BRANCH_VIEW', 'View branches', 'See the shop''s branches and per-branch stock.', 'INVENTORY', 60),
 ('BRANCH_MANAGE', 'Manage branches', 'Create and edit branches and assign users to them.', 'INVENTORY', 61),
 ('STOCK_TRANSFER_MANAGE', 'Transfer stock between branches', 'Record a stock transfer from one branch to another.', 'INVENTORY', 62),
 ('BACKUP_MANAGE', 'Manage backups', 'Take and download backups of the shop''s data.', 'SETTINGS', 90);

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code = 'BRANCH_VIEW'
WHERE r.role_code IN ('OWNER', 'MANAGER', 'ACCOUNTANT', 'STAFF');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code = 'STOCK_TRANSFER_MANAGE'
WHERE r.role_code IN ('OWNER', 'MANAGER');

INSERT INTO role_permission (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM role r JOIN permission p ON p.permission_code IN ('BRANCH_MANAGE', 'BACKUP_MANAGE')
WHERE r.role_code = 'OWNER';

-- ---------------------------------------------------------------------
-- 4. Transfer numbers come from the shared document sequence (CR-041).
-- ---------------------------------------------------------------------
ALTER TABLE document_sequence DROP CONSTRAINT ck_document_sequence_doc_type;
ALTER TABLE document_sequence ADD CONSTRAINT ck_document_sequence_doc_type CHECK (doc_type IN (
    'CUSTOMER', 'SUPPLIER', 'PRODUCT', 'CATEGORY', 'BRAND',
    'INVOICE', 'QUOTATION', 'PURCHASE', 'PROJECT',
    'SALES_ORDER', 'DELIVERY_CHALLAN', 'CREDIT_NOTE', 'STOCK_TRANSFER'
));

-- ---------------------------------------------------------------------
-- 5. A row inserted without a branch belongs to MAIN - by definition the
--    branch every unattributed row was backfilled onto above. Application
--    code always sets branch_id explicitly (BranchContext); this covers
--    the dev/test seed scripts (V9xx, written before branches existed and
--    never edited - rule 1) and any future direct SQL.
-- ---------------------------------------------------------------------
CREATE OR REPLACE FUNCTION branch_default_main() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.branch_id IS NULL THEN
        SELECT b.branch_id INTO NEW.branch_id FROM branch b
        WHERE b.tenant_id = NEW.tenant_id AND b.is_main;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stock_movement_branch_default BEFORE INSERT ON stock_movement
    FOR EACH ROW EXECUTE FUNCTION branch_default_main();
CREATE TRIGGER trg_invoice_branch_default BEFORE INSERT ON invoice
    FOR EACH ROW EXECUTE FUNCTION branch_default_main();
CREATE TRIGGER trg_purchase_branch_default BEFORE INSERT ON purchase
    FOR EACH ROW EXECUTE FUNCTION branch_default_main();

-- A tenant registered after this migration needs its MAIN branch too;
-- TenantRegistrationServiceImpl creates it, and this trigger guarantees it
-- for a tenant row inserted by seed or SQL.
CREATE OR REPLACE FUNCTION tenant_create_main_branch() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO branch (tenant_id, branch_code, branch_name, address_line1, city, state_code, pincode, phone, is_main, status, created_at)
    VALUES (NEW.tenant_id, 'MAIN', NEW.name, NEW.address_line1, NEW.city, NEW.state_code, NEW.pincode, NEW.phone, TRUE, 'ACTIVE', now())
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_tenant_main_branch AFTER INSERT ON tenant
    FOR EACH ROW EXECUTE FUNCTION tenant_create_main_branch();
