-- =====================================================================
-- MULTI-TENANT FOUNDATION (CR-016)
--
-- Reverses the project's original "single shop, not multi-tenant" decision.
-- Shared database, shared schema, tenant_id discriminator column - see
-- CR-016 in CHANGE_REQUEST_REGISTRY.md for the full design, including why
-- mobile_no/email stay globally unique (the login identifier trade-off) and
-- why role/supplier uniqueness moves to per-tenant.
-- =====================================================================

CREATE TABLE tenant (
    tenant_id  BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    slug       VARCHAR(60)  NOT NULL,
    name       VARCHAR(200) NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    CONSTRAINT pk_tenant PRIMARY KEY (tenant_id),
    CONSTRAINT uk_tenant_slug UNIQUE (slug),
    CONSTRAINT ck_tenant_status CHECK (status IN ('ACTIVE', 'SUSPENDED'))
);

-- One tenant so every existing row (dev seed or a real deployment already
-- past BUG-ENV-001) has somewhere to attach. Everything created from here
-- backfills to this row via the DEFAULT below, which is then dropped so no
-- future INSERT can silently omit tenant_id.
INSERT INTO tenant (tenant_id, slug, name, status, created_at)
VALUES (1, 'default', 'Default Shop', 'ACTIVE', CURRENT_TIMESTAMP);

-- Keeps the identity sequence ahead of the row inserted with an explicit id.
SELECT setval(pg_get_serial_sequence('tenant', 'tenant_id'), 1, true);

-- ---------------------------------------------------------------------
-- role : code/name move from globally unique to unique per tenant. Each
-- shop gets its own OWNER/MANAGER/ACCOUNTANT/STAFF rows.
-- ---------------------------------------------------------------------
ALTER TABLE role ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1
    REFERENCES tenant (tenant_id);
ALTER TABLE role ALTER COLUMN tenant_id DROP DEFAULT;

ALTER TABLE role DROP CONSTRAINT uk_role_code;
ALTER TABLE role ADD CONSTRAINT uk_role_code UNIQUE (tenant_id, role_code);

DROP INDEX uk_role_name_lower;
CREATE UNIQUE INDEX uk_role_name_lower ON role (tenant_id, lower(role_name));

CREATE INDEX idx_role_tenant ON role (tenant_id);

-- ---------------------------------------------------------------------
-- app_user : tenant-owned. mobile_no/email stay globally unique - a
-- deliberate CR-016 trade-off, not an oversight - because login has no
-- tenant selector and an identifier must resolve to one user platform-wide.
-- employee_code is an internal HR code and moves to unique per tenant.
-- ---------------------------------------------------------------------
ALTER TABLE app_user ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1
    REFERENCES tenant (tenant_id);
ALTER TABLE app_user ALTER COLUMN tenant_id DROP DEFAULT;

ALTER TABLE app_user DROP CONSTRAINT uk_user_employee_code;
ALTER TABLE app_user ADD CONSTRAINT uk_user_employee_code
    UNIQUE (tenant_id, employee_code);

CREATE INDEX idx_user_tenant ON app_user (tenant_id);

-- ---------------------------------------------------------------------
-- supplier : tenant-owned. supplier_code and the functional unique indexes
-- on name/GST move from global to per-tenant - each shop starts its own
-- SUP-0001.
-- ---------------------------------------------------------------------
ALTER TABLE supplier ADD COLUMN tenant_id BIGINT NOT NULL DEFAULT 1
    REFERENCES tenant (tenant_id);
ALTER TABLE supplier ALTER COLUMN tenant_id DROP DEFAULT;

ALTER TABLE supplier DROP CONSTRAINT uk_supplier_code;
ALTER TABLE supplier ADD CONSTRAINT uk_supplier_code
    UNIQUE (tenant_id, supplier_code);

DROP INDEX uk_supplier_name_lower;
CREATE UNIQUE INDEX uk_supplier_name_lower
    ON supplier (tenant_id, lower(supplier_name)) WHERE deleted_at IS NULL;

DROP INDEX uk_supplier_gst_lower;
CREATE UNIQUE INDEX uk_supplier_gst_lower
    ON supplier (tenant_id, upper(gst_no)) WHERE deleted_at IS NULL AND gst_no IS NOT NULL;

CREATE INDEX idx_supplier_tenant ON supplier (tenant_id);

CREATE TRIGGER trg_tenant_updated_at
    BEFORE UPDATE ON tenant
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON TABLE tenant IS
    'One row per shop (CR-016). Every tenant-owned table carries tenant_id, enforced server-side from the JWT-derived principal, never from client input.';
