-- =====================================================================
-- MODULE 3 : CATEGORIES, BRANDS, PRODUCTS
-- Tenant-owned from the first migration (CR-016) - no retrofit needed,
-- unlike Modules 1 and 2 which predate multi-tenancy.
--
-- Product Variant (multiple sizes/finishes per product, price history,
-- the CR-004 loss-sale approval workflow) is a deliberately separate,
-- later increment layered on top of this. Current pricing lives directly
-- on product for now, so a single-SKU hardware item is sellable the
-- moment this migration lands.
-- =====================================================================

-- ---------------------------------------------------------------------
-- category : hierarchical (FEATURE_REGISTRY Module 4). Never hard-deleted
-- while referenced by a product - see fk_product_category RESTRICT below.
-- ---------------------------------------------------------------------
CREATE TABLE category (
    category_id        BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id           BIGINT       NOT NULL,
    category_code       VARCHAR(30)  NOT NULL,
    category_name       VARCHAR(150) NOT NULL,
    parent_category_id  BIGINT,
    description         VARCHAR(255),
    status               VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_category PRIMARY KEY (category_id),
    CONSTRAINT fk_category_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_category_parent FOREIGN KEY (parent_category_id)
        REFERENCES category (category_id) ON DELETE RESTRICT,
    CONSTRAINT uk_category_code UNIQUE (tenant_id, category_code),
    CONSTRAINT ck_category_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX uk_category_name_lower ON category (tenant_id, lower(category_name));
CREATE INDEX idx_category_tenant ON category (tenant_id);
CREATE INDEX idx_category_parent ON category (parent_category_id);

CREATE TRIGGER trg_category_updated_at
    BEFORE UPDATE ON category
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- brand (FEATURE_REGISTRY Module 5)
-- ---------------------------------------------------------------------
CREATE TABLE brand (
    brand_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id  BIGINT       NOT NULL,
    brand_code VARCHAR(30)  NOT NULL,
    brand_name VARCHAR(150) NOT NULL,
    description VARCHAR(255),
    status     VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_brand PRIMARY KEY (brand_id),
    CONSTRAINT fk_brand_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT uk_brand_code UNIQUE (tenant_id, brand_code),
    CONSTRAINT ck_brand_status CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE UNIQUE INDEX uk_brand_name_lower ON brand (tenant_id, lower(brand_name));
CREATE INDEX idx_brand_tenant ON brand (tenant_id);

CREATE TRIGGER trg_brand_updated_at
    BEFORE UPDATE ON brand
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- product (FEATURE_REGISTRY Module 6). Identification priority is
-- barcode -> manufacturer_code -> model_no -> product_code, never name
-- alone - all four are carried here so that lookup order is possible.
--
-- Never hard-deleted: Module 8 (Purchase), 9 (Inventory) and 11 (Invoice)
-- will reference product_id permanently, exactly like supplier_id today.
-- ---------------------------------------------------------------------
CREATE TABLE product (
    product_id         BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id          BIGINT        NOT NULL,
    product_code       VARCHAR(30)   NOT NULL,
    product_name       VARCHAR(255)  NOT NULL,
    category_id        BIGINT,
    brand_id           BIGINT,
    model_no           VARCHAR(60),
    manufacturer_code  VARCHAR(60),
    barcode            VARCHAR(60),
    unit               VARCHAR(20)   NOT NULL,
    description        TEXT,
    hsn_code           VARCHAR(10),
    -- Percentage, e.g. 18.00. Indian GST slabs are 0/5/12/18/28 today but the
    -- column is not CHECK-constrained to that list - the slab set has
    -- changed before and will again.
    gst_rate_percent   DECIMAL(5,2)  NOT NULL DEFAULT 0,
    -- Current price only. Product Variant (a later increment) adds
    -- product_price_history so a master price change never rewrites what an
    -- already-issued invoice line recorded (PROJECT_SKILLS #17).
    purchase_price_paise BIGINT      NOT NULL DEFAULT 0,
    selling_price_paise  BIGINT      NOT NULL DEFAULT 0,
    mrp_paise             BIGINT      NOT NULL DEFAULT 0,
    minimum_stock      DECIMAL(18,4) NOT NULL DEFAULT 0,
    reorder_level      DECIMAL(18,4) NOT NULL DEFAULT 0,
    status             VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',
    deleted_at         TIMESTAMP(3),
    deleted_by         BIGINT,
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT pk_product PRIMARY KEY (product_id),
    CONSTRAINT fk_product_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_product_category FOREIGN KEY (category_id)
        REFERENCES category (category_id) ON DELETE RESTRICT,
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id)
        REFERENCES brand (brand_id) ON DELETE RESTRICT,
    CONSTRAINT uk_product_code UNIQUE (tenant_id, product_code),
    CONSTRAINT ck_product_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_product_gst CHECK (gst_rate_percent >= 0 AND gst_rate_percent <= 100),
    CONSTRAINT ck_product_prices CHECK (
        purchase_price_paise >= 0 AND selling_price_paise >= 0 AND mrp_paise >= 0),
    CONSTRAINT ck_product_stock CHECK (minimum_stock >= 0 AND reorder_level >= 0)
);

CREATE UNIQUE INDEX uk_product_name_lower
    ON product (tenant_id, lower(product_name)) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uk_product_barcode
    ON product (tenant_id, barcode) WHERE deleted_at IS NULL AND barcode IS NOT NULL;
CREATE INDEX idx_product_tenant   ON product (tenant_id);
CREATE INDEX idx_product_category ON product (category_id);
CREATE INDEX idx_product_brand    ON product (brand_id);
CREATE INDEX idx_product_status   ON product (status, deleted_at);
CREATE INDEX idx_product_active   ON product (product_id) WHERE deleted_at IS NULL;

CREATE TRIGGER trg_product_updated_at
    BEFORE UPDATE ON product
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMENT ON COLUMN product.purchase_price_paise IS
    'Current price, in paise. Never rewritten by a batch import - see product_price_history in a future migration.';
