-- =====================================================================
-- MODULE 4 : INVENTORY
-- Tenant-owned from the first migration (CR-016). Single-location per shop
-- for now - no warehouse table yet, matching how a single hardware shop
-- actually operates. Adding multi-location later is a new column plus a
-- migration, not a rewrite (CR-021).
--
-- stock is one row per (tenant, product): the current quantity on hand.
-- stock_movement is append-only and is the audit trail every quantity
-- change is derived from - stock.quantity_on_hand is a cached total, never
-- the source of truth on its own (PROJECT_SKILLS #24: record only what
-- changed, not the whole row - same reasoning as the supplier history table).
-- =====================================================================

CREATE TABLE stock (
    stock_id          BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id         BIGINT        NOT NULL,
    product_id        BIGINT        NOT NULL,
    quantity_on_hand  DECIMAL(18,4) NOT NULL DEFAULT 0,
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT pk_stock PRIMARY KEY (stock_id),
    CONSTRAINT fk_stock_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_stock_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT uk_stock_product UNIQUE (tenant_id, product_id)
);

CREATE INDEX idx_stock_tenant ON stock (tenant_id);

CREATE TRIGGER trg_stock_updated_at
    BEFORE UPDATE ON stock
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- stock_movement : append-only. quantity_change is signed - positive for
-- stock coming in, negative for stock going out. balance_after is the
-- resulting quantity_on_hand at the moment of this movement, so a history
-- screen never has to replay the whole ledger to show a running total.
-- ---------------------------------------------------------------------
CREATE TABLE stock_movement (
    stock_movement_id BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id         BIGINT        NOT NULL,
    product_id        BIGINT        NOT NULL,
    movement_type     VARCHAR(20)   NOT NULL,
    quantity_change   DECIMAL(18,4) NOT NULL,
    balance_after     DECIMAL(18,4) NOT NULL,
    reference_type    VARCHAR(30),
    reference_id      BIGINT,
    notes             VARCHAR(255),
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    CONSTRAINT pk_stock_movement PRIMARY KEY (stock_movement_id),
    CONSTRAINT fk_stock_movement_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_stock_movement_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT ck_stock_movement_type CHECK (
        movement_type IN ('INITIAL', 'ADJUSTMENT', 'SALE', 'SALE_REVERSAL'))
);

CREATE INDEX idx_stock_movement_tenant  ON stock_movement (tenant_id);
CREATE INDEX idx_stock_movement_product ON stock_movement (tenant_id, product_id, created_at);

COMMENT ON COLUMN stock_movement.quantity_change IS
    'Signed. Positive = stock added, negative = stock removed. Never updated once written.';
