-- =====================================================================
-- MODULE 7 (with a minimal Module 5 stub) : CUSTOMER, INVOICE, PAYMENT
-- See CR-021: built ahead of full Customer management by explicit owner
-- request. `customer` here is intentionally forward-compatible with the
-- real Module 5 (same tenant-scoping / code-generation shape as supplier
-- and product), but nothing outside InvoiceServiceImpl writes to it yet -
-- there is no CustomerController and no Customer management UI.
-- =====================================================================

CREATE TABLE customer (
    customer_id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id         BIGINT       NOT NULL,
    customer_code     VARCHAR(30)  NOT NULL,
    customer_name     VARCHAR(255) NOT NULL,
    mobile_no         VARCHAR(15)  NOT NULL,
    email             VARCHAR(255),
    gst_no            VARCHAR(15),
    credit_limit_paise BIGINT      NOT NULL DEFAULT 0,
    status            VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT pk_customer PRIMARY KEY (customer_id),
    CONSTRAINT fk_customer_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT uk_customer_code   UNIQUE (tenant_id, customer_code),
    -- Auto-match-by-mobile in the invoice flow depends on this being unique
    -- per tenant - two customers sharing a mobile number would make the
    -- match ambiguous.
    CONSTRAINT uk_customer_mobile UNIQUE (tenant_id, mobile_no),
    CONSTRAINT ck_customer_status CHECK (status IN ('ACTIVE', 'INACTIVE')),
    CONSTRAINT ck_customer_credit_limit CHECK (credit_limit_paise >= 0)
);

CREATE INDEX idx_customer_tenant ON customer (tenant_id);

CREATE TRIGGER trg_customer_updated_at
    BEFORE UPDATE ON customer
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- invoice : paid_paise and status are always derived from the linked
-- payment rows, never set directly by a client - the same "never trust
-- client-supplied authoritative state" principle CR-016 applies to
-- tenant_id (SecurityUtils.requireCurrentTenantId()).
-- ---------------------------------------------------------------------
CREATE TABLE invoice (
    invoice_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    tenant_id        BIGINT        NOT NULL,
    invoice_number   VARCHAR(30)   NOT NULL,
    customer_id      BIGINT        NOT NULL,
    invoice_date     DATE          NOT NULL,
    subtotal_paise   BIGINT        NOT NULL,
    gst_amount_paise BIGINT        NOT NULL,
    total_paise      BIGINT        NOT NULL,
    paid_paise       BIGINT        NOT NULL DEFAULT 0,
    balance_paise    BIGINT        NOT NULL,
    status           VARCHAR(20)   NOT NULL DEFAULT 'UNPAID',
    remarks          VARCHAR(500),
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    updated_at TIMESTAMP(3),
    updated_by BIGINT,
    version    INTEGER       NOT NULL DEFAULT 0,
    CONSTRAINT pk_invoice PRIMARY KEY (invoice_id),
    CONSTRAINT fk_invoice_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_invoice_customer FOREIGN KEY (customer_id)
        REFERENCES customer (customer_id),
    CONSTRAINT uk_invoice_number UNIQUE (tenant_id, invoice_number),
    CONSTRAINT ck_invoice_status CHECK (
        status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')),
    CONSTRAINT ck_invoice_amounts CHECK (
        subtotal_paise >= 0 AND gst_amount_paise >= 0 AND total_paise >= 0
        AND paid_paise >= 0 AND paid_paise <= total_paise)
);

CREATE INDEX idx_invoice_tenant   ON invoice (tenant_id);
CREATE INDEX idx_invoice_customer ON invoice (customer_id);
CREATE INDEX idx_invoice_status   ON invoice (tenant_id, status);

CREATE TRIGGER trg_invoice_updated_at
    BEFORE UPDATE ON invoice
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------
-- invoice_item : unit_price_paise and gst_rate_percent are snapshots at
-- sale time (PROJECT_SKILLS #17) - a later change to product.selling_price
-- must never rewrite an already-issued invoice line.
-- ---------------------------------------------------------------------
CREATE TABLE invoice_item (
    invoice_item_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    invoice_id           BIGINT        NOT NULL,
    product_id           BIGINT        NOT NULL,
    product_name_snapshot VARCHAR(255) NOT NULL,
    quantity             DECIMAL(18,4) NOT NULL,
    unit_price_paise     BIGINT        NOT NULL,
    gst_rate_percent     DECIMAL(5,2)  NOT NULL DEFAULT 0,
    line_subtotal_paise  BIGINT        NOT NULL,
    line_gst_paise       BIGINT        NOT NULL,
    line_total_paise     BIGINT        NOT NULL,
    CONSTRAINT pk_invoice_item PRIMARY KEY (invoice_item_id),
    CONSTRAINT fk_invoice_item_invoice FOREIGN KEY (invoice_id)
        REFERENCES invoice (invoice_id) ON DELETE CASCADE,
    CONSTRAINT fk_invoice_item_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT ck_invoice_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_invoice_item_amounts CHECK (
        unit_price_paise >= 0 AND line_subtotal_paise >= 0
        AND line_gst_paise >= 0 AND line_total_paise >= 0)
);

CREATE INDEX idx_invoice_item_invoice ON invoice_item (invoice_id);
CREATE INDEX idx_invoice_item_product ON invoice_item (product_id);

-- ---------------------------------------------------------------------
-- payment : the real transaction record. The optional "initial payment"
-- at invoice creation is not a visual subtraction - it is a row here,
-- exactly like a payment recorded any other day.
-- ---------------------------------------------------------------------
CREATE TABLE payment (
    payment_id     BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    tenant_id      BIGINT       NOT NULL,
    invoice_id     BIGINT       NOT NULL,
    amount_paise   BIGINT       NOT NULL,
    payment_method VARCHAR(20)  NOT NULL,
    payment_date   TIMESTAMP(3) NOT NULL,
    notes          VARCHAR(255),
    created_at TIMESTAMP(3) NOT NULL,
    created_by BIGINT,
    CONSTRAINT pk_payment PRIMARY KEY (payment_id),
    CONSTRAINT fk_payment_tenant FOREIGN KEY (tenant_id)
        REFERENCES tenant (tenant_id),
    CONSTRAINT fk_payment_invoice FOREIGN KEY (invoice_id)
        REFERENCES invoice (invoice_id),
    CONSTRAINT ck_payment_amount CHECK (amount_paise > 0),
    CONSTRAINT ck_payment_method CHECK (
        payment_method IN ('CASH', 'UPI', 'CARD', 'BANK_TRANSFER', 'OTHER'))
);

CREATE INDEX idx_payment_tenant  ON payment (tenant_id);
CREATE INDEX idx_payment_invoice ON payment (invoice_id);
